--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists pg_net;

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    -- Valores de los campos personalizados definidos en configuration.config;
    -- clave = value del campo, valor = lo capturado en el formulario.
    custom_fields jsonb not null default '{}'::jsonb
);

create table public.contacts (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    custom_fields jsonb not null default '{}'::jsonb
);

create table public.contact_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    custom_fields jsonb not null default '{}'::jsonb,
    -- Embudo al que pertenece la oportunidad (value de un embudo definido en
    -- configuration.config.dealPipelines). El default coincide con el embudo
    -- que se sintetiza para configuraciones anteriores a los embudos múltiples.
    pipeline text not null default 'ventas',
    -- Motivo por el que se perdió (value de configuration.config.dealLossReasons).
    loss_reason text
);

create table public.deal_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

-- La unicidad es por organización, no global: KontrolIA Auth permite que una
-- misma persona sea miembro de varias organizaciones, y en ese caso necesita
-- una ficha de comercial en cada una.
create unique index uq__sales__organization_id__user_id on public.sales using btree (organization_id, user_id);

create table public.automations (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    active boolean not null default true,
    -- Disparador: qué tiene que pasar (contacts|deals, created|stage_changed).
    trigger_resource text not null,
    trigger_event text not null,
    trigger_params jsonb not null default '{}'::jsonb,
    -- Acción: qué hacer entonces (create_task|assign_owner) y sus parámetros.
    action_type text not null,
    action_params jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

create index automations_organization_id_idx on public.automations (organization_id);

create table public.saved_views (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    -- Lista a la que pertenece la vista (contacts, companies, deals).
    resource text not null,
    name text not null,
    -- { filter, sort } tal como los maneja la lista.
    params jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create index saved_views_organization_id_idx on public.saved_views (organization_id);

create table public.webhooks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    url text not null,
    -- Secreto de firma (X-Vinqulia-Firma = HMAC-SHA256 hex del cuerpo).
    secret text not null default encode(extensions.gen_random_bytes(24), 'hex'),
    -- Tablas suscritas; vacío = todas las notificables.
    resources text[] not null default '{}',
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index webhooks_organization_id_idx on public.webhooks (organization_id);

create table public.tags (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

-- Una fila de configuración por organización. Antes era un singleton
-- (check (id = 1)), lo que impedía que cada empresa tuviera su propia marca,
-- sus etapas de oportunidad o su moneda.
create table public.configuration (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid primary key,
    config jsonb not null default '{}'::jsonb
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.saved_views
    add constraint saved_views_sales_id_fkey foreign key (sales_id) references public.sales(id);

-- sales.user_id NO lleva clave foránea a auth.users: la identidad vive en
-- KontrolIA Auth (otro proyecto Supabase) y el auth.users local no contiene a
-- los usuarios. Es un identificador opaco que valida el servidor vía token.

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

-- Índices de aislamiento por organización.
-- Toda consulta del CRM lleva el filtro de RLS `organization_id = ...`, así que
-- sin estos índices cada lectura degenera en un escaneo secuencial de la tabla
-- completa en cuanto haya varias empresas dentro.
create index if not exists companies_organization_id_idx on public.companies (organization_id);
create index if not exists contacts_organization_id_idx on public.contacts (organization_id);
create index if not exists contact_notes_organization_id_idx on public.contact_notes (organization_id);
create index if not exists deals_organization_id_idx on public.deals (organization_id);
create index if not exists deal_notes_organization_id_idx on public.deal_notes (organization_id);
create index if not exists sales_organization_id_idx on public.sales (organization_id);
create index if not exists tags_organization_id_idx on public.tags (organization_id);
create index if not exists tasks_organization_id_idx on public.tasks (organization_id);
