-- Historial de las oportunidades (crm.deal_events): quién cambió la etapa,
-- el importe, el responsable, o la archivó, y cuándo. Lo escribe la base con
-- un disparador —igual que ticket_events— para que también cuente lo que
-- cambian el kanban, la API o el asistente. La ficha del contacto lo lee en
-- su línea de tiempo (cambios de etapa) y la ficha de la oportunidad lo
-- muestra entero.
--
-- Ver supabase/schemas/01_tables.sql, 02_functions.sql, 03_views.sql,
-- 04_triggers.sql, 05_policies.sql y 06_grants.sql (fuente de verdad).

-- Quién hace el cambio: lo sella el puente /api/datos (imponerActor), como
-- en tickets; con una clave de API queda null y el historial lo muestra
-- como «sistema».
alter table crm.deals add column if not exists updated_by bigint;

create table if not exists crm.deal_events (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    deal_id bigint not null references crm.deals (id) on delete cascade,
    sales_id bigint,
    -- created | stage | amount | sales_id | archived | unarchived
    field text not null,
    old_value text,
    new_value text,
    created_at timestamp with time zone not null default now()
);

create index if not exists deal_events_deal_idx on crm.deal_events (deal_id, created_at);
create index if not exists deal_events_organization_id_idx on crm.deal_events (organization_id);

alter table crm.deal_events enable row level security;

drop policy if exists "Deal events are scoped to the organization" on crm.deal_events;
create policy "Deal events are scoped to the organization" on crm.deal_events
    for select to authenticated
    using (organization_id = crm.current_organization_id());
drop policy if exists "Deal events are created in the organization" on crm.deal_events;
create policy "Deal events are created in the organization" on crm.deal_events
    for insert to authenticated
    with check (organization_id = crm.current_organization_id());

grant select, insert on table crm.deal_events to anon, authenticated, service_role;
grant usage, select on sequence crm.deal_events_id_seq to anon, authenticated, service_role;

create or replace function crm.log_deal_events() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
declare
  actor bigint := new.updated_by;
begin
  if tg_op = 'INSERT' then
    insert into crm.deal_events (organization_id, deal_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, coalesce(actor, new.sales_id), 'created', null, new.stage);
    return new;
  end if;

  if new.stage is distinct from old.stage then
    insert into crm.deal_events (organization_id, deal_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'stage', old.stage, new.stage);
  end if;
  if new.amount is distinct from old.amount then
    insert into crm.deal_events (organization_id, deal_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'amount', old.amount::text, new.amount::text);
  end if;
  if new.sales_id is distinct from old.sales_id then
    insert into crm.deal_events (organization_id, deal_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'sales_id', old.sales_id::text, new.sales_id::text);
  end if;
  if old.archived_at is null and new.archived_at is not null then
    insert into crm.deal_events (organization_id, deal_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'archived', null, new.stage);
  elsif old.archived_at is not null and new.archived_at is null then
    insert into crm.deal_events (organization_id, deal_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'unarchived', null, new.stage);
  end if;
  return new;
end;
$$;

create or replace trigger on_crm_deals_log_events
    after insert or update on crm.deals
    for each row execute function crm.log_deal_events();

-- La línea de tiempo del contacto gana los cambios de etapa de sus
-- oportunidades. Se recrea la vista entera (no admite añadir una rama).
create or replace view crm.contact_timeline with (security_invoker = on) as
select
    ('note.' || cn.id) as id,
    'note' as kind,
    coalesce(cn.type, 'note') as type,
    cn.id as source_id,
    cn.contact_id,
    co.company_id,
    cn.date,
    cn.sales_id,
    null::text as title,
    cn.text,
    cn.status,
    coalesce(array_length(cn.attachments, 1), 0) as attachment_count,
    null::numeric as amount,
    cn.organization_id
from crm.contact_notes cn
    join crm.contacts co on co.id = cn.contact_id
union all
select ('task.' || t.id), 'task', 'task', t.id, t.contact_id, co.company_id, t.due_date, t.sales_id, t.type, t.text, null, 0, null, t.organization_id
from crm.tasks t join crm.contacts co on co.id = t.contact_id
where t.due_date is not null
union all
select ('task_done.' || t.id), 'task', 'task_done', t.id, t.contact_id, co.company_id, t.done_date, t.sales_id, t.type, t.text, null, 0, null, t.organization_id
from crm.tasks t join crm.contacts co on co.id = t.contact_id
where t.done_date is not null
union all
select ('deal.' || d.id), 'deal', 'deal', d.id, co.id, d.company_id, d.created_at, d.sales_id, d.name, d.description, d.stage, 0, d.amount::numeric, d.organization_id
from crm.deals d join crm.contacts co on co.id = any (d.contact_ids)
union all
-- Cambios de etapa: el texto es la etapa nueva (slug) y old_value queda en
-- status para que la interfaz pueda decir «de X a Y».
select ('deal_stage.' || e.id), 'deal', 'deal_stage', d.id, co.id, d.company_id, e.created_at, e.sales_id, d.name, e.new_value, e.old_value, 0, d.amount::numeric, e.organization_id
from crm.deal_events e
    join crm.deals d on d.id = e.deal_id
    join crm.contacts co on co.id = any (d.contact_ids)
where e.field = 'stage'
union all
select ('deal_archived.' || d.id), 'deal', 'deal_archived', d.id, co.id, d.company_id, d.archived_at, d.sales_id, d.name, d.loss_reason, d.stage, 0, d.amount::numeric, d.organization_id
from crm.deals d join crm.contacts co on co.id = any (d.contact_ids)
where d.archived_at is not null
union all
select ('ticket.' || tk.id), 'ticket', 'ticket', tk.id, tk.contact_id, tk.company_id, tk.created_at, tk.sales_id, tk.subject, tk.description, tk.status, 0, null, tk.organization_id
from crm.tickets tk
union all
select ('ticket_closed.' || tk.id), 'ticket', 'ticket_closed', tk.id, tk.contact_id, tk.company_id, tk.closed_at, tk.sales_id, tk.subject, tk.resolution, tk.status, 0, null, tk.organization_id
from crm.tickets tk
where tk.closed_at is not null
union all
select ('quote.' || q.id), 'quote', 'quote', q.id, q.contact_id, q.company_id, q.sent_at, q.sales_id, coalesce(q.title, q.number), q.number, q.status, 0, q.total, q.organization_id
from crm.quotes q
where q.contact_id is not null and q.sent_at is not null
union all
select ('quote_decided.' || q.id), 'quote',
    case when q.accepted_at is not null then 'quote_accepted' else 'quote_rejected' end,
    q.id, q.contact_id, q.company_id, coalesce(q.accepted_at, q.rejected_at), q.sales_id, coalesce(q.title, q.number),
    coalesce(q.accepted_by_name, q.rejection_reason), q.status, 0, q.total, q.organization_id
from crm.quotes q
where q.contact_id is not null and (q.accepted_at is not null or q.rejected_at is not null);
