-- Tickets gestionables.
--
-- Hasta ahora un ticket era una nota con estado: sin prioridad, sin
-- responsable real (sales_id era «quien lo creó» y no se podía cambiar),
-- sin fecha de última actividad (updated_at nunca se actualizaba), sin
-- categoría (iba escondida como prefijo «[categoría]» en el asunto, que es
-- lo que manda el agente de voz), sin cierre con motivo y sin historial.
--
-- Esta migración añade lo que hace falta para GESTIONAR una cola de
-- soporte, sin dependencias externas:
--
--   priority          baja / normal / alta / urgente (configurable en Ajustes)
--   category          configurable en Ajustes; se rellena sola desde el
--                     prefijo «[categoría]» del asunto para seguir siendo
--                     compatible con el agente de voz y los formularios
--   source            manual | web_form | mcp | api | voice_agent | email
--   closed_at         se sella al pasar a «closed» y se limpia al reabrir
--   resolution        motivo de cierre (resuelto, duplicado, sin respuesta…)
--   last_activity_at  último cambio o nota; es lo que ordena la lista
--   updated_by        quién hizo la última modificación; lo inyecta el
--                     puente /api/datos (que escribe con la clave de
--                     servicio, sin JWT, así que auth.uid() no sirve aquí)
--   ticket_events     historial: quién cambió qué y cuándo
--
-- sales_id pasa a significar «responsable» y es editable; por defecto
-- sigue siendo quien creó el ticket (set_sales_id_default / el puente).

alter table crm.tickets
    add column if not exists priority text not null default 'normal',
    add column if not exists category text,
    add column if not exists source text not null default 'manual',
    add column if not exists closed_at timestamp with time zone,
    add column if not exists resolution text,
    add column if not exists last_activity_at timestamp with time zone not null default now(),
    add column if not exists updated_by bigint;

create index if not exists tickets_last_activity_idx
    on crm.tickets (organization_id, last_activity_at desc);
create index if not exists tickets_sales_id_idx on crm.tickets (sales_id);

-- Historial de cambios de un ticket.
create table if not exists crm.ticket_events (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    ticket_id bigint not null references crm.tickets (id) on delete cascade,
    -- Quién lo hizo; null cuando viene de un sistema (formulario, API, agente).
    sales_id bigint,
    -- created | status | priority | category | sales_id
    field text not null,
    old_value text,
    new_value text,
    created_at timestamp with time zone not null default now()
);

create index if not exists ticket_events_ticket_idx
    on crm.ticket_events (ticket_id, created_at);

alter table crm.ticket_events enable row level security;

drop policy if exists "Ticket events are scoped to the organization" on crm.ticket_events;
create policy "Ticket events are scoped to the organization" on crm.ticket_events
    for select to authenticated
    using (organization_id = crm.current_organization_id());
drop policy if exists "Ticket events are created in the organization" on crm.ticket_events;
create policy "Ticket events are created in the organization" on crm.ticket_events
    for insert to authenticated
    with check (organization_id = crm.current_organization_id());

grant select, insert on table crm.ticket_events to anon, authenticated, service_role;
grant usage, select on sequence crm.ticket_events_id_seq to anon, authenticated, service_role;

-- Separa los prefijos «[categoría] [motivo]» del asunto. Devuelve la
-- categoría (primer prefijo, en minúsculas), el motivo (segundo, si lo hay)
-- y el asunto limpio. Misma regla que parseTicketSubject.ts en el cliente.
CREATE OR REPLACE FUNCTION "crm"."ticket_subject_prefixes"("asunto" "text", OUT "categoria" "text", OUT "motivo" "text", OUT "limpio" "text") RETURNS record
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
declare
  resto text := asunto;
  m text[];
  n int := 0;
begin
  categoria := null;
  motivo := null;
  loop
    m := regexp_match(resto, '^\s*\[([^\]]+)\]\s*');
    exit when m is null or n >= 6;
    n := n + 1;
    if n = 1 then
      categoria := lower(btrim(m[1]));
    elsif n = 2 then
      motivo := btrim(m[1]);
    end if;
    resto := substr(resto, length((regexp_match(resto, '^\s*\[[^\]]+\]\s*'))[1]) + 1);
  end loop;
  limpio := coalesce(nullif(btrim(resto), ''), asunto);
end;
$$;

-- Antes de escribir: prefijos → categoría, sellos de fechas y cierre.
CREATE OR REPLACE FUNCTION "crm"."handle_ticket_before_write"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  p record;
begin
  if tg_op = 'INSERT' then
    -- Compatibilidad con el agente de voz y los formularios: el prefijo
    -- «[categoría]» del asunto pasa a la columna, el segundo «[motivo]» a la
    -- descripción si venía vacía, y el asunto queda limpio.
    if new.category is null and new.subject ~ '^\s*\[' then
      select * into p from crm.ticket_subject_prefixes(new.subject);
      new.category := p.categoria;
      if new.description is null and p.motivo is not null then
        new.description := p.motivo;
      end if;
      new.subject := p.limpio;
    end if;
    -- El agente de voz escribe «Prioridad: urgent» en la descripción: si no
    -- vino una prioridad explícita, se toma de ahí.
    if new.priority = 'normal' and new.description ~* 'prioridad:\s*(low|normal|high|urgent)' then
      new.priority := lower((regexp_match(new.description, 'prioridad:\s*(low|normal|high|urgent)', 'i'))[1]);
    end if;
    new.last_activity_at := coalesce(new.last_activity_at, now());
    if new.status = 'closed' then
      new.closed_at := coalesce(new.closed_at, now());
    end if;
    return new;
  end if;

  new.updated_at := now();
  if new.status is distinct from old.status
     or new.priority is distinct from old.priority
     or new.category is distinct from old.category
     or new.sales_id is distinct from old.sales_id then
    new.last_activity_at := now();
  end if;
  if new.status = 'closed' and old.status is distinct from 'closed' then
    new.closed_at := now();
  elsif new.status <> 'closed' and old.status = 'closed' then
    -- Reabrir: el cierre anterior deja de valer, el historial lo conserva.
    new.closed_at := null;
    new.resolution := null;
  end if;
  return new;
end;
$$;

-- Después de escribir: historial de cambios.
CREATE OR REPLACE FUNCTION "crm"."log_ticket_events"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  actor bigint := new.updated_by;
begin
  if tg_op = 'INSERT' then
    insert into crm.ticket_events (organization_id, ticket_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, coalesce(actor, new.sales_id), 'created', null, new.status);
    return new;
  end if;

  if new.status is distinct from old.status then
    insert into crm.ticket_events (organization_id, ticket_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'status', old.status, new.status);
  end if;
  if new.priority is distinct from old.priority then
    insert into crm.ticket_events (organization_id, ticket_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'priority', old.priority, new.priority);
  end if;
  if new.category is distinct from old.category then
    insert into crm.ticket_events (organization_id, ticket_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'category', old.category, new.category);
  end if;
  if new.sales_id is distinct from old.sales_id then
    insert into crm.ticket_events (organization_id, ticket_id, sales_id, field, old_value, new_value)
    values (new.organization_id, new.id, actor, 'sales_id', old.sales_id::text, new.sales_id::text);
  end if;
  return new;
end;
$$;

-- Una nota en el ticket cuenta como actividad.
CREATE OR REPLACE FUNCTION "crm"."handle_ticket_note_created"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  update crm.tickets
     set last_activity_at = greatest(last_activity_at, coalesce(new.date, now())),
         updated_at = now()
   where id = new.ticket_id;
  return new;
end;
$$;

-- Datos existentes: categoría desde el prefijo, última actividad desde las
-- notas, fecha de cierre para los ya cerrados. Va antes de crear los
-- disparadores para no llenar el historial con cambios de relleno.
update crm.tickets t
   set category = p.categoria,
       description = coalesce(t.description, p.motivo),
       subject = p.limpio
  from (
    select id, (crm.ticket_subject_prefixes(subject)).*
      from crm.tickets
     where category is null and subject ~ '^\s*\['
  ) p
 where p.id = t.id;

update crm.tickets t
   set last_activity_at = greatest(
         t.created_at,
         coalesce((select max(n.date) from crm.ticket_notes n where n.ticket_id = t.id), t.created_at)
       );

update crm.tickets
   set closed_at = coalesce(closed_at, updated_at)
 where status = 'closed';

update crm.tickets
   set priority = lower((regexp_match(description, 'prioridad:\s*(low|normal|high|urgent)', 'i'))[1])
 where priority = 'normal' and description ~* 'prioridad:\s*(low|normal|high|urgent)';

drop trigger if exists on_crm_tickets_before_write on crm.tickets;
create trigger on_crm_tickets_before_write
    before insert or update on crm.tickets
    for each row execute function crm.handle_ticket_before_write();

drop trigger if exists on_crm_tickets_log_events on crm.tickets;
create trigger on_crm_tickets_log_events
    after insert or update on crm.tickets
    for each row execute function crm.log_ticket_events();

drop trigger if exists on_crm_ticket_notes_created on crm.ticket_notes;
create trigger on_crm_ticket_notes_created
    after insert on crm.ticket_notes
    for each row execute function crm.handle_ticket_note_created();

