-- Cotizaciones: el documento comercial que sale de una oportunidad.
--
-- Una cotización tiene líneas (descripción, cantidad, precio, descuento e
-- IVA por línea) y un ciclo: borrador → enviada → vista → aceptada /
-- rechazada / vencida. Se envía por correo con un enlace público (token) en
-- el que el cliente la ve y la acepta; al aceptarse, la oportunidad se gana
-- y, con el módulo Clientes activo, nace un contrato o una compra.
--
-- Lo que NO vive aquí, a propósito: el catálogo de productos (se integra) y
-- la factura (la emite Faqturia u otro al recibir el webhook
-- quotes.updated con status = accepted).
--
-- Aditiva y reversible: dos tablas, una de secuencias, tres funciones y
-- sus disparadores.

create table crm.quotes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    -- COT-2026-0001, por organización y año. Lo asigna la base al insertar.
    number text,
    deal_id bigint,
    company_id bigint,
    contact_id bigint,
    title text not null,
    -- draft | sent | viewed | accepted | rejected | expired
    status text not null default 'draft',
    currency text not null default 'MXN',
    valid_until date,
    -- Condiciones, alcance, lo que va debajo de las líneas.
    notes text,
    -- Se recalculan con las líneas (ver crm.recalcular_totales_de_cotizacion).
    subtotal numeric not null default 0,
    tax_total numeric not null default 0,
    total numeric not null default 0,
    -- Si al aceptarse debe nacer un contrato con esta periodicidad:
    -- monthly | quarterly | yearly. Nulo = una compra puntual.
    contract_period text,
    -- Enlace público. 256 bits de azar; no se adivina.
    public_token text not null default (
      replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '')
    ),
    sent_at timestamp with time zone,
    viewed_at timestamp with time zone,
    accepted_at timestamp with time zone,
    accepted_by_name text,
    accepted_by_email text,
    rejected_at timestamp with time zone,
    rejection_reason text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table crm.quotes
    add constraint quotes_deal_id_fkey foreign key (deal_id) references crm.deals(id) on delete set null,
    add constraint quotes_company_id_fkey foreign key (company_id) references crm.companies(id) on delete set null,
    add constraint quotes_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on delete set null,
    add constraint quotes_sales_id_fkey foreign key (sales_id) references crm.sales(id),
    add constraint quotes_status_check check (status in ('draft','sent','viewed','accepted','rejected','expired')),
    add constraint quotes_contract_period_check check (contract_period is null or contract_period in ('monthly','quarterly','yearly'));

create unique index quotes_public_token_uk on crm.quotes (public_token);
create unique index quotes_organization_number_uk on crm.quotes (organization_id, number);
create index quotes_organization_id_idx on crm.quotes (organization_id);
create index quotes_deal_id_idx on crm.quotes (deal_id);
create index quotes_company_id_idx on crm.quotes (company_id);

create table crm.quote_items (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    quote_id bigint not null,
    position integer not null default 0,
    description text not null,
    -- Referencia en el catálogo externo (Faqturia u otro), si la hay.
    product_ref text,
    quantity numeric not null default 1,
    unit_price numeric not null default 0,
    discount_pct numeric not null default 0,
    -- IVA de la línea, en porcentaje. Se captura sin IVA y se suma abajo.
    tax_rate numeric not null default 16,
    amount numeric generated always as (
      round(quantity * unit_price * (1 - discount_pct / 100), 2)
    ) stored
);

alter table crm.quote_items
    add constraint quote_items_quote_id_fkey foreign key (quote_id) references crm.quotes(id) on delete cascade,
    add constraint quote_items_discount_check check (discount_pct >= 0 and discount_pct <= 100),
    add constraint quote_items_tax_check check (tax_rate >= 0);

create index quote_items_quote_id_idx on crm.quote_items (quote_id);
create index quote_items_organization_id_idx on crm.quote_items (organization_id);

-- Folio por organización y año, con bloqueo de fila: dos altas a la vez no
-- pueden llevarse el mismo número.
create table crm.quote_sequences (
    organization_id uuid not null,
    year integer not null,
    last_number integer not null default 0,
    primary key (organization_id, year)
);

create or replace function crm.next_quote_number(org uuid) returns text
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  anio integer := extract(year from now())::integer;
  siguiente integer;
begin
  insert into crm.quote_sequences (organization_id, year, last_number)
  values (org, anio, 1)
  on conflict (organization_id, year)
    do update set last_number = crm.quote_sequences.last_number + 1
  returning last_number into siguiente;
  return 'COT-' || anio || '-' || lpad(siguiente::text, 4, '0');
end;
$$;

revoke all on function crm.next_quote_number(uuid) from public;
grant all on function crm.next_quote_number(uuid) to authenticated, service_role;

create or replace function crm.set_quote_number() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
begin
  if new.number is null then
    new.number := crm.next_quote_number(new.organization_id);
  end if;
  return new;
end;
$$;

create trigger set_quote_number_trigger
    before insert on crm.quotes
    for each row execute function crm.set_quote_number();

-- Totales: se recalculan en la base con cada cambio de líneas. Así un
-- cliente que escribe líneas por la API no puede dejar un total que no
-- cuadre con ellas.
create or replace function crm.recalcular_totales_de_cotizacion() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  cotizacion bigint := coalesce(new.quote_id, old.quote_id);
begin
  update crm.quotes q
     set subtotal = t.subtotal,
         tax_total = t.tax_total,
         total = t.subtotal + t.tax_total,
         updated_at = now()
    from (
      select coalesce(sum(amount), 0) as subtotal,
             coalesce(sum(round(amount * tax_rate / 100, 2)), 0) as tax_total
        from crm.quote_items
       where quote_id = cotizacion
    ) t
   where q.id = cotizacion;
  return null;
end;
$$;

create trigger recalcular_totales_de_cotizacion_trigger
    after insert or update or delete on crm.quote_items
    for each row execute function crm.recalcular_totales_de_cotizacion();

-- La organización de la línea es la de su cotización: no se acepta del
-- cliente ni se deja en blanco cuando escribe la clave de servicio.
create or replace function crm.set_quote_item_organization() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
begin
  select organization_id into new.organization_id from crm.quotes where id = new.quote_id;
  return new;
end;
$$;

create trigger set_quote_item_organization_trigger
    before insert on crm.quote_items
    for each row execute function crm.set_quote_item_organization();

create trigger set_quote_sales_id_trigger
    before insert on crm.quotes
    for each row execute function crm.set_sales_id_default();

-- Webhooks: quotes.created / updated / deleted, como el resto de recursos.
create trigger notify_webhooks_quotes
    after insert or update or delete on crm.quotes
    for each row execute function crm.notify_webhooks();

-- RLS: las cuatro políticas por organización, como en contratos.
alter table crm.quotes enable row level security;
alter table crm.quote_items enable row level security;
alter table crm.quote_sequences enable row level security;

create policy "Quotes are scoped to the organization" on crm.quotes
    for select to authenticated using (organization_id = crm.current_organization_id());
create policy "Quotes are created in the organization" on crm.quotes
    for insert to authenticated with check (organization_id = crm.current_organization_id());
create policy "Quotes are updated within the organization" on crm.quotes
    for update to authenticated using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Quotes are deleted within the organization" on crm.quotes
    for delete to authenticated using (organization_id = crm.current_organization_id());

create policy "Quote items are scoped to the organization" on crm.quote_items
    for select to authenticated using (organization_id = crm.current_organization_id());
create policy "Quote items are created in the organization" on crm.quote_items
    for insert to authenticated with check (
      exists (select 1 from crm.quotes q where q.id = quote_id and q.organization_id = crm.current_organization_id())
    );
create policy "Quote items are updated within the organization" on crm.quote_items
    for update to authenticated using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Quote items are deleted within the organization" on crm.quote_items
    for delete to authenticated using (organization_id = crm.current_organization_id());

-- Las secuencias solo las toca la función (security definer): sin políticas.

grant select, insert, update, delete on table crm.quotes to anon, authenticated, service_role;
grant usage, select on sequence crm.quotes_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on table crm.quote_items to anon, authenticated, service_role;
grant usage, select on sequence crm.quote_items_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on table crm.quote_sequences to service_role;
revoke all on table crm.quote_sequences from anon;
revoke all on table crm.quote_sequences from authenticated;
