-- Vistas guardadas: filtros y orden de una lista, con nombre, compartidos
-- con toda la organización («Clientes calientes de CDMX»). Sin esto, cada
-- quien rehace sus filtros cada mañana.
--
-- `params` guarda { filter, sort } tal como los maneja la lista; `resource`
-- dice a qué lista pertenece (contacts, companies, deals).

create table public.saved_views (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    resource text not null,
    name text not null,
    params jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

alter table public.saved_views
    add constraint saved_views_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index saved_views_organization_id_idx on public.saved_views (organization_id);

alter table public.saved_views enable row level security;

create policy "Saved views are scoped to the organization" on public.saved_views
    for select to authenticated
    using (organization_id = public.current_organization_id());
create policy "Saved views are created in the organization" on public.saved_views
    for insert to authenticated
    with check (organization_id = public.current_organization_id());
create policy "Saved views are updated within the organization" on public.saved_views
    for update to authenticated
    using (organization_id = public.current_organization_id())
    with check (organization_id = public.current_organization_id());
create policy "Saved views are deleted within the organization" on public.saved_views
    for delete to authenticated
    using (organization_id = public.current_organization_id());

-- Grants explícitos: los default privileges de la instalación pueden estar
-- definidos por otro rol y no cubrir tablas creadas después.
grant select, insert, update, delete on table public.saved_views to anon, authenticated, service_role;
grant usage, select on sequence public.saved_views_id_seq to anon, authenticated, service_role;
