-- Claves de API: acceso de servidor a servidor para integraciones externas
-- (por ejemplo, un formulario de captación en otro sitio con sus propios
-- campos). El secreto en claro nunca se guarda, solo su hash; se genera y se
-- muestra una única vez desde /api/claves. Ver src/lib/server/apiKeys.ts.
create table crm.api_keys (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    key_prefix text not null,
    key_hash text not null unique,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    last_used_at timestamp with time zone
);

create index api_keys_organization_id_idx on crm.api_keys (organization_id);

alter table crm.api_keys enable row level security;

-- Como configuration: cualquiera de la organización puede ver que existen,
-- pero solo un administrador puede crear, activar/desactivar o borrar una
-- clave, porque una clave de API da acceso a los datos como si fuera un
-- miembro más.
create policy "Api keys are scoped to the organization" on crm.api_keys
    for select to authenticated
    using (organization_id = crm.current_organization_id() and crm.is_admin());
create policy "Api keys are created by organization admins" on crm.api_keys
    for insert to authenticated
    with check (organization_id = crm.current_organization_id() and crm.is_admin());
create policy "Api keys are updated by organization admins" on crm.api_keys
    for update to authenticated
    using (organization_id = crm.current_organization_id() and crm.is_admin())
    with check (organization_id = crm.current_organization_id() and crm.is_admin());
create policy "Api keys are deleted by organization admins" on crm.api_keys
    for delete to authenticated
    using (organization_id = crm.current_organization_id() and crm.is_admin());

grant select, insert, update, delete on table crm.api_keys to anon, authenticated, service_role;
grant usage, select on sequence crm.api_keys_id_seq to anon, authenticated, service_role;
