-- Webhooks: filtro por evento, cola de entregas con reintentos y protección
-- contra bucles.
--
-- Antes, el disparador hacía el POST en el momento con pg_net y se tragaba
-- cualquier error: un receptor caído significaba un aviso perdido para
-- siempre. Ahora el disparador solo ENCOLA (barato y transaccional) y un
-- despachador programado envía y reintenta.
--
-- Nada de esto es específico de ningún cliente: cualquier organización que
-- integre Vinqulia con otro sistema necesita lo mismo.

-- ── Suscripción por evento, no solo por tabla ──────────────────────────
-- '{}' = todos los eventos de los recursos suscritos, que es como se
-- comportaba antes: las suscripciones existentes no cambian de conducta.
alter table crm.webhooks
    add column if not exists events text[] not null default '{}';

comment on column crm.webhooks.events is
  'Eventos concretos a los que se suscribe (contacts.created, deals.updated…). Vacío = todos los del recurso. Es lo que permite evitar bucles: un sistema que responde a «created» escribiendo en la ficha no debe suscribirse a «updated».';

-- ── Cola de entregas ───────────────────────────────────────────────────
create table crm.webhook_deliveries (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    webhook_id bigint not null,
    -- Identificador estable del evento, viaja en la cabecera para que el
    -- receptor pueda descartar duplicados por su cuenta.
    event_id uuid not null default extensions.gen_random_uuid(),
    event text not null,
    resource text not null,
    payload jsonb not null,
    attempts integer not null default 0,
    max_attempts integer not null default 5,
    next_attempt_at timestamp with time zone not null default now(),
    delivered_at timestamp with time zone,
    -- Identificador de la petición en pg_net mientras está en vuelo; se
    -- limpia al reconciliar la respuesta.
    net_request_id bigint,
    last_status_code integer,
    last_error text,
    created_at timestamp with time zone not null default now()
);

alter table crm.webhook_deliveries
    add constraint webhook_deliveries_webhook_id_fkey
    foreign key (webhook_id) references crm.webhooks(id) on delete cascade;

-- Índice del despachador: lo pendiente que ya toca enviar.
create index webhook_deliveries_pendientes_idx
    on crm.webhook_deliveries (next_attempt_at)
    where delivered_at is null;
create index webhook_deliveries_en_vuelo_idx
    on crm.webhook_deliveries (net_request_id)
    where net_request_id is not null;
create index webhook_deliveries_organization_id_idx
    on crm.webhook_deliveries (organization_id);

alter table crm.webhook_deliveries enable row level security;

-- Solo lectura para la organización: la cola la escribe el disparador
-- (SECURITY DEFINER) y la gestiona el despachador, no el usuario.
create policy "Webhook deliveries are scoped to the organization" on crm.webhook_deliveries
    for select to authenticated
    using (organization_id = crm.current_organization_id());

grant select on table crm.webhook_deliveries to anon, authenticated, service_role;
grant usage, select on sequence crm.webhook_deliveries_id_seq to anon, authenticated, service_role;

-- ── El disparador ahora encola en vez de enviar ────────────────────────
create or replace function crm.notify_webhooks() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  registro jsonb;
  org uuid;
  evento text;
  suscripcion record;
begin
  -- Cascadas dentro de la misma transacción: si una automatización o un
  -- disparador escribe a raíz de este mismo cambio, no se vuelve a avisar.
  -- No protege del bucle ENTRE sistemas (esa escritura llega en otra
  -- transacción); para eso está el filtro de eventos de más abajo.
  if pg_trigger_depth() > 1 then
    return null;
  end if;

  if tg_op = 'DELETE' then
    registro := to_jsonb(old);
  else
    registro := to_jsonb(new);
  end if;

  org := (registro ->> 'organization_id')::uuid;
  if org is null then
    return null;
  end if;

  -- Un UPDATE que deja la fila idéntica no es noticia. Corta el rebote más
  -- típico: el sistema externo reescribe el mismo valor que ya estaba.
  if tg_op = 'UPDATE' and to_jsonb(old) = to_jsonb(new) then
    return null;
  end if;

  evento := tg_table_name || '.' || case tg_op
    when 'INSERT' then 'created'
    when 'UPDATE' then 'updated'
    else 'deleted'
  end;

  for suscripcion in
    select id from crm.webhooks
    where organization_id = org
      and active
      and (resources = '{}' or tg_table_name = any(resources))
      and (events = '{}' or evento = any(events))
  loop
    insert into crm.webhook_deliveries
      (organization_id, webhook_id, event, resource, payload)
    values (
      org,
      suscripcion.id,
      evento,
      tg_table_name,
      jsonb_build_object(
        'evento', evento,
        'recurso', tg_table_name,
        'fecha', now(),
        'datos', registro
      )
    );
  end loop;

  return null;
end;
$$;

grant all on function crm.notify_webhooks() to authenticated;
grant all on function crm.notify_webhooks() to service_role;

-- ── Reconciliación: mirar qué contestó cada envío en vuelo ─────────────
create or replace function crm.reconciliar_webhooks() returns integer
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  entrega record;
  respuesta record;
  cerradas integer := 0;
begin
  for entrega in
    select id, net_request_id, attempts, max_attempts
    from crm.webhook_deliveries
    where net_request_id is not null and delivered_at is null
  loop
    select status_code, error_msg, timed_out
      into respuesta
      from net._http_response
     where id = entrega.net_request_id;

    -- Todavía en vuelo: pg_net aún no ha escrito la respuesta.
    continue when not found;

    if respuesta.status_code between 200 and 299 then
      update crm.webhook_deliveries
         set delivered_at = now(),
             net_request_id = null,
             last_status_code = respuesta.status_code,
             last_error = null
       where id = entrega.id;
    else
      -- Espera creciente: 1, 3, 9, 27 y 81 minutos.
      update crm.webhook_deliveries
         set net_request_id = null,
             last_status_code = respuesta.status_code,
             last_error = coalesce(
               respuesta.error_msg,
               case when respuesta.timed_out then 'timeout' else null end,
               'HTTP ' || coalesce(respuesta.status_code::text, '?')
             ),
             next_attempt_at = now() + (interval '1 minute' * power(3, entrega.attempts))
       where id = entrega.id;
    end if;

    cerradas := cerradas + 1;
  end loop;

  return cerradas;
end;
$$;

grant all on function crm.reconciliar_webhooks() to service_role;

-- ── Despacho: firmar y enviar lo que toca ──────────────────────────────
create or replace function crm.despachar_webhooks(lote integer default 50)
returns integer
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  entrega record;
  cuerpo text;
  firma text;
  peticion bigint;
  enviadas integer := 0;
begin
  perform crm.reconciliar_webhooks();

  for entrega in
    select d.id, d.payload, d.event, d.event_id, d.attempts, w.url, w.secret
      from crm.webhook_deliveries d
      join crm.webhooks w on w.id = d.webhook_id
     where d.delivered_at is null
       and d.net_request_id is null
       and d.attempts < d.max_attempts
       and d.next_attempt_at <= now()
       and w.active
     order by d.next_attempt_at
     limit lote
     for update of d skip locked
  loop
    begin
      -- Se firma exactamente el texto que pg_net envía: su cuerpo es este
      -- mismo jsonb serializado con ::text (comprobado byte a byte).
      cuerpo := entrega.payload::text;
      firma := encode(
        extensions.hmac(cuerpo, entrega.secret, 'sha256'),
        'hex'
      );

      peticion := net.http_post(
        url := entrega.url,
        body := entrega.payload,
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'X-Vinqulia-Evento', entrega.event,
          'X-Vinqulia-Evento-Id', entrega.event_id::text,
          'X-Vinqulia-Intento', (entrega.attempts + 1)::text,
          'X-Vinqulia-Firma', firma
        )
      );

      update crm.webhook_deliveries
         set attempts = attempts + 1,
             net_request_id = peticion,
             -- Si la respuesta nunca llega, el siguiente ciclo lo reintenta
             -- igualmente en vez de dejarlo colgado para siempre.
             next_attempt_at = now() + (interval '1 minute' * power(3, attempts + 1))
       where id = entrega.id;

      enviadas := enviadas + 1;
    exception when others then
      update crm.webhook_deliveries
         set attempts = attempts + 1,
             last_error = sqlerrm,
             next_attempt_at = now() + (interval '1 minute' * power(3, attempts + 1))
       where id = entrega.id;
    end;
  end loop;

  return enviadas;
end;
$$;

grant all on function crm.despachar_webhooks(integer) to service_role;

-- ── Programación ───────────────────────────────────────────────────────
create extension if not exists pg_cron;

select cron.schedule(
  'despachar-webhooks',
  '* * * * *',
  $$select crm.despachar_webhooks();$$
);
