-- Tickets de soporte, asociados siempre a un contacto y a su empresa.
create table crm.tickets (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    subject text not null,
    description text,
    status text not null default 'open',
    contact_id bigint not null,
    company_id bigint not null,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index tickets_organization_id_idx on crm.tickets (organization_id);
create index tickets_contact_id_idx on crm.tickets (contact_id);
create index tickets_company_id_idx on crm.tickets (company_id);

alter table crm.tickets
    add constraint tickets_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.tickets enable row level security;

create policy "Tickets are scoped to the organization" on crm.tickets
    for select to authenticated
    using (organization_id = crm.current_organization_id());
create policy "Tickets are created in the organization" on crm.tickets
    for insert to authenticated
    with check (organization_id = crm.current_organization_id());
create policy "Tickets are updated within the organization" on crm.tickets
    for update to authenticated
    using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Tickets are deleted within the organization" on crm.tickets
    for delete to authenticated
    using (organization_id = crm.current_organization_id());

create trigger set_ticket_sales_id_trigger
    before insert on crm.tickets
    for each row execute function crm.set_sales_id_default();

create trigger notify_webhooks_tickets
    after insert or update or delete on crm.tickets
    for each row execute function crm.notify_webhooks();

grant select, insert, update, delete on table crm.tickets to anon, authenticated, service_role;
grant usage, select on sequence crm.tickets_id_seq to anon, authenticated, service_role;

-- Los formularios públicos ahora pueden crear un ticket en vez de un
-- contacto. "lead" preserva el comportamiento actual para los formularios
-- ya existentes.
alter table crm.public_forms
    add column if not exists type text not null default 'lead';
