-- Plantillas de correo y proveedor de IA para generarlas.
--
-- Dos tablas con tratamientos distintos a propósito:
--
--   email_templates  es contenido normal de la organización (nombre, asunto,
--                    cuerpo). Se sirve por el puente /api/datos como cualquier
--                    otro recurso, con su RLS por organización.
--
--   ai_settings      guarda la clave del proveedor de IA, un secreto
--                    reutilizable. Mismo tratamiento que email_settings: sin
--                    grants para anon/authenticated, RLS sin políticas, y en
--                    la lista de recursos prohibidos del puente.

create table crm.email_templates (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    subject text not null,
    -- HTML del cuerpo, con los campos de fusión como {{contacto.nombre}}.
    body_html text not null default '',
    -- Logo de la plantilla, si se subió uno (URL del bucket de adjuntos).
    logo_url text,
    active boolean not null default true,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table crm.email_templates
    add constraint email_templates_sales_id_fkey
    foreign key (sales_id) references crm.sales(id);

create index email_templates_organization_id_idx
    on crm.email_templates (organization_id);

alter table crm.email_templates enable row level security;

create policy "Email templates are scoped to the organization" on crm.email_templates
    for select to authenticated
    using (organization_id = crm.current_organization_id());
create policy "Email templates are created in the organization" on crm.email_templates
    for insert to authenticated
    with check (organization_id = crm.current_organization_id());
create policy "Email templates are updated within the organization" on crm.email_templates
    for update to authenticated
    using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Email templates are deleted within the organization" on crm.email_templates
    for delete to authenticated
    using (organization_id = crm.current_organization_id());

grant select, insert, update, delete on table crm.email_templates to anon, authenticated, service_role;
grant usage, select on sequence crm.email_templates_id_seq to anon, authenticated, service_role;

create trigger set_email_templates_sales_id_trigger
    before insert on crm.email_templates
    for each row execute function crm.set_sales_id_default();

-- Proveedor de IA de la organización, para generar el contenido de las
-- plantillas a partir de una descripción.
create table crm.ai_settings (
    organization_id uuid not null primary key default (auth.jwt() ->> 'organization_id')::uuid,
    provider text not null check (provider in ('claude', 'openai', 'deepseek')),
    api_key text not null,
    -- Vacío = el modelo por defecto del proveedor, resuelto en el servidor.
    model text,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table crm.ai_settings enable row level security;

grant select, insert, update, delete on table crm.ai_settings to service_role;

-- Imprescindible: los default privileges del esquema crm conceden
-- `grant all on tables` a anon y authenticated a TODA tabla nueva, así que
-- esta los recibiría pese al grant de arriba. Sin revocarlos, la protección
-- quedaría colgando solo de que RLS no tenga políticas.
revoke all on table crm.ai_settings from anon;
revoke all on table crm.ai_settings from authenticated;
