-- Módulo Afiliados: primer módulo activable por organización (el estado de
-- activación vive en crm.configuration.config.modules, sin migración propia).
-- Ver apps/crm/src/components/crm/modules/registry.ts y
-- apps/crm/src/components/crm/affiliates/ para la parte de aplicación.

create table crm.affiliates (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    company_id bigint not null,
    deal_id bigint,
    referral_code text not null
        check (referral_code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    commission_percentage numeric,
    active boolean not null default true,
    kontrolia_auth_user_id uuid,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create unique index affiliates_organization_contact_uk
    on crm.affiliates (organization_id, contact_id);
create unique index affiliates_organization_referral_code_uk
    on crm.affiliates (organization_id, referral_code);
create index affiliates_organization_id_idx on crm.affiliates (organization_id);
create index affiliates_kontrolia_auth_user_id_idx
    on crm.affiliates (kontrolia_auth_user_id);

alter table crm.affiliates
    add constraint affiliates_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;
alter table crm.affiliates
    add constraint affiliates_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;
alter table crm.affiliates
    add constraint affiliates_deal_id_fkey foreign key (deal_id) references crm.deals(id) on update cascade on delete set null;
alter table crm.affiliates
    add constraint affiliates_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.affiliates enable row level security;

create policy "Affiliates are scoped to the organization" on crm.affiliates
    for select to authenticated
    using (organization_id = crm.current_organization_id());
create policy "Affiliates are created in the organization" on crm.affiliates
    for insert to authenticated
    with check (organization_id = crm.current_organization_id());
create policy "Affiliates are updated within the organization" on crm.affiliates
    for update to authenticated
    using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Affiliates are deleted within the organization" on crm.affiliates
    for delete to authenticated
    using (organization_id = crm.current_organization_id());
create policy "Affiliates can see their own row" on crm.affiliates
    for select to authenticated
    using (kontrolia_auth_user_id = auth.uid());

create trigger set_affiliates_sales_id_trigger
    before insert on crm.affiliates
    for each row execute function crm.set_sales_id_default();

grant select, insert, update, delete on table crm.affiliates to anon, authenticated, service_role;
grant usage, select on sequence crm.affiliates_id_seq to anon, authenticated, service_role;

create or replace function crm.generar_codigo_referido_disponible(
  org uuid,
  contacto bigint
) returns text
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  base text;
  candidato text;
  intento int := 0;
begin
  select regexp_replace(lower(coalesce(first_name, '') || '-' || coalesce(last_name, '')), '[^a-z0-9]+', '-', 'g')
    into base
    from crm.contacts
   where id = contacto;

  base := trim(both '-' from coalesce(base, ''));
  if base = '' then
    base := 'afiliado';
  end if;

  loop
    candidato := case when intento = 0 then base else base || '-' || substr(md5(random()::text), 1, 5) end;

    exit when not exists (
      select 1 from crm.affiliates
       where organization_id = org and referral_code = candidato
    );

    intento := intento + 1;
    if intento > 20 then
      candidato := 'afiliado-' || substr(md5(random()::text || clock_timestamp()::text), 1, 10);
      exit;
    end if;
  end loop;

  return candidato;
end;
$$;

grant all on function crm.generar_codigo_referido_disponible(uuid, bigint) to service_role;

create or replace function crm.gestionar_modulo_afiliados() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  org uuid;
  cfg jsonb;
  pipeline_id text;
  etapas_completas jsonb;
  contacto bigint;
  empresa bigint;
  codigo text;
begin
  if old.stage is not distinct from new.stage then
    return null;
  end if;

  org := new.organization_id;
  if org is null then
    return null;
  end if;

  begin
    select config -> 'modules' -> 'affiliates' into cfg
      from crm.configuration
     where organization_id = org;

    if cfg is null or coalesce((cfg ->> 'active')::boolean, false) is not true then
      return null;
    end if;

    pipeline_id := cfg ->> 'pipelineId';
    etapas_completas := cfg -> 'completionStages';

    if pipeline_id is null or etapas_completas is null then
      return null;
    end if;

    if new.pipeline is distinct from pipeline_id then
      return null;
    end if;

    if not (etapas_completas ? new.stage) then
      return null;
    end if;

    contacto := new.contact_ids[1];
    if contacto is null then
      return null;
    end if;

    select company_id into empresa from crm.contacts where id = contacto;
    if empresa is null then
      return null;
    end if;

    codigo := crm.generar_codigo_referido_disponible(org, contacto);

    insert into crm.affiliates (organization_id, contact_id, company_id, deal_id, referral_code)
    values (org, contacto, empresa, new.id, codigo)
    on conflict (organization_id, contact_id) do update
      set company_id = excluded.company_id,
          deal_id = excluded.deal_id,
          updated_at = now();
  exception when others then
    null;
  end;

  return null;
end;
$$;

grant all on function crm.gestionar_modulo_afiliados() to authenticated;
grant all on function crm.gestionar_modulo_afiliados() to service_role;

create trigger gestionar_modulo_afiliados_deals
    after update on crm.deals
    for each row execute function crm.gestionar_modulo_afiliados();
