-- Notas de seguimiento sobre un ticket de soporte, con el mismo modelo que
-- deal_notes (sin campo status propio: el ticket ya tiene el suyo).
create table crm.ticket_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    type text not null default 'note',
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create index ticket_notes_ticket_id_idx on crm.ticket_notes using btree (ticket_id);
create index if not exists ticket_notes_organization_id_idx on crm.ticket_notes (organization_id);

alter table crm.ticket_notes
    add constraint ticket_notes_ticket_id_fkey foreign key (ticket_id) references crm.tickets(id) on update cascade on delete cascade;

alter table crm.ticket_notes
    add constraint ticket_notes_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.ticket_notes enable row level security;

create policy "Ticket notes are scoped to the organization" on crm.ticket_notes
    for select to authenticated
    using (organization_id = crm.current_organization_id());
create policy "Ticket notes are created in the organization" on crm.ticket_notes
    for insert to authenticated
    with check (organization_id = crm.current_organization_id());
create policy "Ticket notes are updated within the organization" on crm.ticket_notes
    for update to authenticated
    using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Ticket notes are deleted within the organization" on crm.ticket_notes
    for delete to authenticated
    using (organization_id = crm.current_organization_id());

create trigger set_ticket_notes_sales_id_trigger
    before insert on crm.ticket_notes
    for each row execute function crm.set_sales_id_default();

create trigger on_ticket_notes_attachments_updated_delete_note_attachments
    after update on crm.ticket_notes
    for each row
    when (old.attachments is distinct from new.attachments)
    execute function crm.cleanup_note_attachments();

create trigger on_ticket_notes_deleted_delete_note_attachments
    after delete on crm.ticket_notes
    for each row execute function crm.cleanup_note_attachments();

create trigger notify_webhooks_ticket_notes
    after insert or update or delete on crm.ticket_notes
    for each row execute function crm.notify_webhooks();

grant select, insert, update, delete on table crm.ticket_notes to anon, authenticated, service_role;
grant usage, select on sequence crm.ticket_notes_id_seq to anon, authenticated, service_role;
