-- Conectores: catálogo de productos y facturación NO se construyen dentro
-- del CRM. El cliente elige a su proveedor (Shopify para productos, Faqturia
-- para facturar…), lo conecta con sus propias credenciales y el CRM lee
-- productos y pide/recupera facturas por API. Una familia, un conector
-- activo por organización.
--
-- Aditiva: tres tablas nuevas y dos columnas fiscales en companies.

-- 1. El conector en sí. Guarda la credencial del proveedor en claro, igual
--    que email_settings: hay que presentarla en cada llamada, así que no
--    puede ser un hash. Por eso es una tabla SOLO de service_role, fuera del
--    puente /api/datos (RECURSOS_PROHIBIDOS) y con rutas propias que exigen
--    ser administrador y nunca devuelven el secreto.
create table crm.connectors (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    family text not null check (family in ('products', 'invoicing')),
    provider text not null,
    -- Lo que no es secreto: dominio de la tienda, URL de la instalación,
    -- serie y claves SAT por defecto…
    settings jsonb not null default '{}'::jsonb,
    secret text not null,
    status text not null default 'connected' check (status in ('connected', 'error')),
    last_error text,
    last_checked_at timestamp with time zone,
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
create unique index connectors_org_family_uk on crm.connectors (organization_id, family);

alter table crm.connectors enable row level security;
-- Sin políticas: nadie salvo service_role la lee.
grant select, insert, update, delete on table crm.connectors to service_role;
grant usage, select on sequence crm.connectors_id_seq to service_role;
revoke all on table crm.connectors from anon;
revoke all on table crm.connectors from authenticated;
revoke all on sequence crm.connectors_id_seq from anon;
revoke all on sequence crm.connectors_id_seq from authenticated;

-- 2. Espejo del catálogo del proveedor, para elegir líneas de cotización
--    sin salir a la API en cada tecla. Lo escribe solo el servidor al
--    sincronizar; la organización lo lee.
create table crm.products (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    connector_id bigint not null,
    provider text not null,
    external_id text not null,
    sku text,
    name text not null,
    description text,
    unit_price numeric(14,2) not null default 0,
    currency text not null default 'MXN',
    active boolean not null default true,
    image_url text,
    synced_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now()
);
alter table crm.products
    add constraint products_connector_id_fkey foreign key (connector_id) references crm.connectors(id) on delete cascade;
create unique index products_org_provider_external_uk on crm.products (organization_id, provider, external_id);
create index products_organization_id_idx on crm.products (organization_id, active);

alter table crm.products enable row level security;
create policy "Products are scoped to the organization" on crm.products
    for select to authenticated using (organization_id = crm.current_organization_id());
-- Primero se quita lo que los default privileges conceden solo (grant
-- all, truncate incluido) y luego se da solo lectura.
revoke all on table crm.products from anon;
revoke all on table crm.products from authenticated;
grant select on table crm.products to anon, authenticated;
grant select, insert, update, delete on table crm.products to service_role;
grant usage, select on sequence crm.products_id_seq to anon, authenticated, service_role;

-- 3. Las facturas que el proveedor emitió por encargo del CRM. El CRM no
--    genera CFDI: guarda la referencia (id externo, UUID, serie y folio) para
--    enseñarla y descargar PDF/XML del proveedor cuando haga falta.
create table crm.invoices (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    connector_id bigint,
    provider text not null,
    quote_id bigint,
    company_id bigint,
    external_id text not null,
    uuid text,
    serie text,
    folio text,
    status text not null check (status in ('stamped', 'draft', 'cancelled', 'error')),
    total numeric(14,2) not null default 0,
    currency text not null default 'MXN',
    issued_at timestamp with time zone,
    error text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
alter table crm.invoices
    add constraint invoices_connector_id_fkey foreign key (connector_id) references crm.connectors(id) on delete set null,
    add constraint invoices_quote_id_fkey foreign key (quote_id) references crm.quotes(id) on delete set null,
    add constraint invoices_company_id_fkey foreign key (company_id) references crm.companies(id) on delete set null;
create unique index invoices_org_provider_external_uk on crm.invoices (organization_id, provider, external_id);
create index invoices_quote_id_idx on crm.invoices (quote_id);
create index invoices_organization_id_idx on crm.invoices (organization_id, created_at);

alter table crm.invoices enable row level security;
create policy "Invoices are scoped to the organization" on crm.invoices
    for select to authenticated using (organization_id = crm.current_organization_id());
-- Primero se quita lo que los default privileges conceden solo (grant
-- all, truncate incluido) y luego se da solo lectura.
revoke all on table crm.invoices from anon;
revoke all on table crm.invoices from authenticated;
grant select on table crm.invoices to anon, authenticated;
grant select, insert, update, delete on table crm.invoices to service_role;
grant usage, select on sequence crm.invoices_id_seq to anon, authenticated, service_role;

-- 4. Datos fiscales del receptor que el CFDI exige y la empresa no tenía:
--    régimen fiscal y uso de CFDI (RFC y código postal ya existen).
alter table crm.companies add column if not exists tax_regime text;
alter table crm.companies add column if not exists cfdi_use text;
