-- Módulo Clientes: qué ha comprado y qué tiene contratado cada cliente.
--
-- Hasta ahora el CRM acompañaba hasta cerrar la venta y ahí se acababa: una
-- oportunidad ganada guarda un importe, nada más. No había forma de saber qué
-- compró un cliente, qué tiene contratado ni cuándo le vence — y sin eso no se
-- le puede ofrecer lo siguiente.
--
-- DÓNDE VIVE CADA COSA. El catálogo de productos, las existencias y la
-- facturación son de OTROS sistemas (Faqturia, un ERP ajeno, una tienda). El
-- CRM no los duplica: guarda lo que necesita para vender más, y cada fila
-- recuerda de dónde vino (`source`) y con qué identificador (`external_id`).
--
-- La descripción y el precio SÍ se guardan en cada línea, y eso no es una
-- copia que haya que mantener al día: es la foto del momento. Si mañana el
-- producto cambia de nombre o de precio, la compra de ayer debe seguir
-- diciendo qué se vendió y a cuánto, igual que una factura.

-- Etapa del ciclo de vida: prospecto, cliente activo, en riesgo, perdido.
-- Los valores los define cada organización en configuration.config, como el
-- resto de catálogos; aquí solo se guarda el elegido.
alter table crm.companies
    add column if not exists lifecycle_stage text;

create index if not exists companies_lifecycle_stage_idx
    on crm.companies (organization_id, lifecycle_stage);

-- Contratos y suscripciones: la relación que DURA.
--
-- Se modela con periodos y no como "una compra que se repite" porque es lo
-- que permite lo que de verdad se pregunta: qué está activo hoy, qué vence el
-- mes que viene, qué se pausó y qué cambió de importe por el camino.
create table crm.contracts (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    name text not null,
    -- active | paused | cancelled | expired
    status text not null default 'active',
    -- monthly | quarterly | yearly | one_time
    billing_period text,
    amount numeric,
    currency text not null default 'MXN',
    started_on date,
    -- Próxima renovación o vencimiento: es la fecha sobre la que se avisa.
    renews_on date,
    ended_on date,
    auto_renew boolean not null default true,
    -- De dónde salió: manual, faqturia, el ERP del cliente, una tienda…
    source text not null default 'manual',
    external_id text,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Compras: los HECHOS puntuales (una factura, un pedido, un cobro).
create table crm.purchases (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    -- Si la compra corresponde a un contrato (una mensualidad, por ejemplo).
    contract_id bigint,
    -- Número visible en el sistema de origen (folio de factura, nº de pedido).
    reference text,
    purchased_on date not null default current_date,
    amount numeric not null default 0,
    currency text not null default 'MXN',
    -- paid | pending | cancelled | refunded
    status text not null default 'paid',
    source text not null default 'manual',
    external_id text,
    created_at timestamp with time zone not null default now()
);

-- Líneas de la compra: el QUÉ. `description` y `unit_price` son la foto del
-- momento; `product_ref` es el identificador del producto en el sistema de
-- origen, que es lo que permite preguntar «quién tiene X y no Y».
create table crm.purchase_items (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    purchase_id bigint not null,
    description text not null,
    product_ref text,
    quantity numeric not null default 1,
    unit_price numeric,
    amount numeric
);

alter table crm.contracts
    add constraint contracts_company_id_fkey
    foreign key (company_id) references crm.companies(id) on delete cascade;
alter table crm.contracts
    add constraint contracts_sales_id_fkey
    foreign key (sales_id) references crm.sales(id);

alter table crm.purchases
    add constraint purchases_company_id_fkey
    foreign key (company_id) references crm.companies(id) on delete cascade;
alter table crm.purchases
    add constraint purchases_contract_id_fkey
    foreign key (contract_id) references crm.contracts(id) on delete set null;

alter table crm.purchase_items
    add constraint purchase_items_purchase_id_fkey
    foreign key (purchase_id) references crm.purchases(id) on delete cascade;

create index contracts_company_id_idx on crm.contracts (company_id);
create index contracts_renews_on_idx on crm.contracts (organization_id, renews_on)
    where status = 'active';
create index purchases_company_id_idx on crm.purchases (company_id);
create index purchases_purchased_on_idx on crm.purchases (organization_id, purchased_on);
create index purchase_items_purchase_id_idx on crm.purchase_items (purchase_id);
create index purchase_items_product_ref_idx on crm.purchase_items (organization_id, product_ref);

-- Idempotencia de la integración: si el sistema de origen reenvía la misma
-- factura —y lo hará, por un reintento o una resincronización— no debe
-- duplicarse. Es la diferencia entre una integración que sirve y una que
-- ensucia la base.
create unique index contracts_source_external_uk
    on crm.contracts (organization_id, source, external_id)
    where external_id is not null;
create unique index purchases_source_external_uk
    on crm.purchases (organization_id, source, external_id)
    where external_id is not null;

alter table crm.contracts enable row level security;
alter table crm.purchases enable row level security;
alter table crm.purchase_items enable row level security;

create policy "Contracts are scoped to the organization" on crm.contracts
    for select to authenticated using (organization_id = crm.current_organization_id());
create policy "Contracts are created in the organization" on crm.contracts
    for insert to authenticated with check (organization_id = crm.current_organization_id());
create policy "Contracts are updated within the organization" on crm.contracts
    for update to authenticated using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Contracts are deleted within the organization" on crm.contracts
    for delete to authenticated using (organization_id = crm.current_organization_id());

create policy "Purchases are scoped to the organization" on crm.purchases
    for select to authenticated using (organization_id = crm.current_organization_id());
create policy "Purchases are created in the organization" on crm.purchases
    for insert to authenticated with check (organization_id = crm.current_organization_id());
create policy "Purchases are updated within the organization" on crm.purchases
    for update to authenticated using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Purchases are deleted within the organization" on crm.purchases
    for delete to authenticated using (organization_id = crm.current_organization_id());

create policy "Purchase items are scoped to the organization" on crm.purchase_items
    for select to authenticated using (organization_id = crm.current_organization_id());
create policy "Purchase items are created in the organization" on crm.purchase_items
    for insert to authenticated with check (organization_id = crm.current_organization_id());
create policy "Purchase items are updated within the organization" on crm.purchase_items
    for update to authenticated using (organization_id = crm.current_organization_id())
    with check (organization_id = crm.current_organization_id());
create policy "Purchase items are deleted within the organization" on crm.purchase_items
    for delete to authenticated using (organization_id = crm.current_organization_id());

grant select, insert, update, delete on table crm.contracts to anon, authenticated, service_role;
grant usage, select on sequence crm.contracts_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on table crm.purchases to anon, authenticated, service_role;
grant usage, select on sequence crm.purchases_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on table crm.purchase_items to anon, authenticated, service_role;
grant usage, select on sequence crm.purchase_items_id_seq to anon, authenticated, service_role;

create trigger set_contracts_sales_id_trigger
    before insert on crm.contracts
    for each row execute function crm.set_sales_id_default();

-- Todo lo que ha hecho un cliente, en una fila por empresa. Es lo que
-- responde «¿cuánto vale este cliente y qué tiene contratado?» sin recorrer
-- sus compras una por una.
create or replace view crm.customer_summary with (security_invoker = on) as
select
    c.id,
    c.organization_id,
    c.name,
    c.lifecycle_stage,
    c.sales_id,
    coalesce(p.nb_purchases, 0) as nb_purchases,
    coalesce(p.total_spent, 0) as total_spent,
    p.first_purchase_on,
    p.last_purchase_on,
    coalesce(k.nb_active_contracts, 0) as nb_active_contracts,
    coalesce(k.recurring_amount, 0) as recurring_amount,
    k.next_renewal_on
from crm.companies c
left join lateral (
    select count(*) as nb_purchases,
           sum(amount) as total_spent,
           min(purchased_on) as first_purchase_on,
           max(purchased_on) as last_purchase_on
      from crm.purchases
     where company_id = c.id and status <> 'cancelled'
) p on true
left join lateral (
    select count(*) as nb_active_contracts,
           sum(amount) as recurring_amount,
           min(renews_on) filter (where renews_on is not null) as next_renewal_on
      from crm.contracts
     where company_id = c.id and status = 'active'
) k on true;

grant select on table crm.customer_summary to anon, authenticated, service_role;
