-- Automatización «cuando pase X, envía el correo de la plantilla Y».
--
-- Por qué una cola y no un envío directo desde el disparador: armar el
-- correo exige el diseño de plantillaBase.ts y resolver los campos de fusión
-- con valoresDeFusion.ts, ambos en TypeScript. Reescribir eso en plpgsql
-- serían dos implementaciones del mismo render que se desincronizarían a la
-- primera plantilla nueva.
--
-- Así que el disparador solo ENCOLA —barato y dentro de la misma transacción
-- que el cambio— y un despachador programado avisa a la aplicación, que es
-- quien sabe renderizar y enviar. Mismo reparto que con los webhooks.

create table crm.email_outbox (
    organization_id uuid not null,
    id bigint generated by default as identity primary key,
    automation_id bigint,
    template_id bigint not null,
    contact_id bigint not null,
    -- La oportunidad que originó el envío, si la regla venía de un deal:
    -- es lo que permite usar {{oportunidad.*}} en la plantilla.
    deal_id bigint,
    attempts integer not null default 0,
    max_attempts integer not null default 5,
    next_attempt_at timestamp with time zone not null default now(),
    sent_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone not null default now()
);

alter table crm.email_outbox
    add constraint email_outbox_template_id_fkey
    foreign key (template_id) references crm.email_templates(id) on delete cascade;
alter table crm.email_outbox
    add constraint email_outbox_contact_id_fkey
    foreign key (contact_id) references crm.contacts(id) on delete cascade;
alter table crm.email_outbox
    add constraint email_outbox_deal_id_fkey
    foreign key (deal_id) references crm.deals(id) on delete set null;

create index email_outbox_pendientes_idx
    on crm.email_outbox (next_attempt_at)
    where sent_at is null;
create index email_outbox_organization_id_idx
    on crm.email_outbox (organization_id);

alter table crm.email_outbox enable row level security;

-- Solo lectura, para poder consultar qué se envió y qué falló. La cola la
-- escribe el disparador y la gestiona el despachador, ambos con privilegios.
create policy "Email outbox is scoped to the organization" on crm.email_outbox
    for select to authenticated
    using (organization_id = crm.current_organization_id());

grant select on table crm.email_outbox to anon, authenticated, service_role;
grant usage, select on sequence crm.email_outbox_id_seq to anon, authenticated, service_role;

-- Ajustes internos de la instalación (no de una organización): con qué
-- secreto se autentica el despachador contra la aplicación, y en qué
-- dirección vive esa aplicación.
--
-- Guarda un secreto, así que recibe el mismo trato que email_settings: sin
-- grants para anon/authenticated y RLS sin políticas. El revoke explícito es
-- imprescindible porque los default privileges del esquema conceden
-- `grant all on tables` a toda tabla nueva.
create table crm.internal_settings (
    key text primary key,
    value text not null,
    updated_at timestamp with time zone not null default now()
);

alter table crm.internal_settings enable row level security;
grant select, insert, update, delete on table crm.internal_settings to service_role;
revoke all on table crm.internal_settings from anon;
revoke all on table crm.internal_settings from authenticated;

insert into crm.internal_settings (key, value)
values ('dispatch_secret', encode(extensions.gen_random_bytes(32), 'hex'))
on conflict (key) do nothing;

-- Dirección de la aplicación. Sin ella el despachador no hace nada: es lo
-- que hay que ajustar al instalar Vinqulia en otro dominio.
insert into crm.internal_settings (key, value)
values ('app_url', 'https://crm.kontrolia.io')
on conflict (key) do nothing;

-- El disparador aprende a encolar correos.
create or replace function crm.run_automations() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  org uuid;
  evento text;
  etapa text;
  regla record;
  contacto bigint;
  responsable bigint;
  plantilla bigint;
begin
  -- Una automatizacion puede provocar otra escritura (crear una tarea, por
  -- ejemplo). Sin este corte, esa escritura volveria a disparar el motor.
  if pg_trigger_depth() > 1 then
    return null;
  end if;

  org := new.organization_id;
  if org is null then
    return null;
  end if;

  if tg_op = 'INSERT' then
    evento := 'created';
  elsif tg_table_name = 'deals' and new.stage is distinct from old.stage then
    evento := 'stage_changed';
  else
    return null;
  end if;

  if tg_table_name = 'deals' then
    etapa := new.stage;
  end if;

  for regla in
    select id, name, action_type, action_params, trigger_params
      from crm.automations
     where organization_id = org
       and active
       and trigger_resource = tg_table_name
       and trigger_event = evento
  loop
    begin
      -- Una regla acotada a una etapa solo se aplica en esa etapa.
      if evento = 'stage_changed'
         and nullif(regla.trigger_params ->> 'stage', '') is not null
         and regla.trigger_params ->> 'stage' is distinct from etapa then
        continue;
      end if;

      -- Contacto al que apunta la regla. Las tareas y los correos cuelgan
      -- siempre de uno; en una oportunidad se usa su primer contacto.
      if tg_table_name = 'contacts' then
        contacto := new.id;
      else
        contacto := new.contact_ids[1];
      end if;

      if regla.action_type = 'create_task' then
        if contacto is not null then
          insert into crm.tasks
            (organization_id, contact_id, text, type, due_date, sales_id)
          values (
            org,
            contacto,
            coalesce(nullif(regla.action_params ->> 'text', ''), regla.name),
            nullif(regla.action_params ->> 'taskType', ''),
            -- Sin dias, la tarea queda SIN vencimiento: no todo lo que
            -- genera una automatizacion tiene fecha limite, y poner una
            -- inventada llena el calendario de plazos que nadie pacto.
            case
              when regla.action_params ->> 'dueInDays' ~ '^[0-9]+$'
              then now() + (
                (regla.action_params ->> 'dueInDays') || ' days'
              )::interval
              else null
            end,
            new.sales_id
          );
        end if;

      elsif regla.action_type = 'assign_owner' then
        responsable := nullif(regla.action_params ->> 'salesId', '')::bigint;
        if responsable is not null then
          if tg_table_name = 'contacts' then
            update crm.contacts set sales_id = responsable where id = new.id;
          else
            update crm.deals set sales_id = responsable where id = new.id;
          end if;
        end if;

      elsif regla.action_type = 'send_email' then
        plantilla := nullif(regla.action_params ->> 'templateId', '')::bigint;

        -- Solo se encola si la plantilla sigue existiendo y activa en esta
        -- organizacion: una plantilla borrada o apagada no debe mandar nada.
        if contacto is not null and plantilla is not null
           and exists (
             select 1 from crm.email_templates
              where id = plantilla and organization_id = org and active
           ) then
          insert into crm.email_outbox
            (organization_id, automation_id, template_id, contact_id, deal_id)
          values (
            org,
            regla.id,
            plantilla,
            contacto,
            case when tg_table_name = 'deals' then new.id else null end
          );
        end if;
      end if;

    exception when others then
      null; -- una regla rota jamas debe tumbar la escritura original
    end;
  end loop;

  return null;
end;
$$;

grant all on function crm.run_automations() to authenticated;
grant all on function crm.run_automations() to service_role;

-- Avisa a la aplicación de que hay correos pendientes. No envía: la
-- aplicación es la que sabe armar la plantilla y hablar con el proveedor.
create or replace function crm.despachar_correos() returns integer
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  pendientes integer;
  destino text;
  secreto text;
begin
  select count(*) into pendientes
    from crm.email_outbox
   where sent_at is null
     and attempts < max_attempts
     and next_attempt_at <= now();

  if pendientes = 0 then
    return 0;
  end if;

  select value into destino from crm.internal_settings where key = 'app_url';
  select value into secreto from crm.internal_settings where key = 'dispatch_secret';

  if destino is null or secreto is null then
    return 0;
  end if;

  perform net.http_post(
    url := rtrim(destino, '/') || '/api/correos/despachar',
    body := '{}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'X-Vinqulia-Despacho', secreto
    ),
    timeout_milliseconds := 30000
  );

  return pendientes;
end;
$$;

grant all on function crm.despachar_correos() to service_role;

select cron.schedule(
  'despachar-correos',
  '* * * * *',
  $$select crm.despachar_correos();$$
);
