--
-- Tables
-- This file declares all tables in the crm schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists pg_net;

-- Esquema del CRM: todo el contenido de esta aplicacion vive aqui, separado
-- del esquema public para poder compartir el proyecto de Supabase con otras
-- aplicaciones del ecosistema KontrolIA sin colisionar nombres.
create schema if not exists crm;

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table crm.companies (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    -- Valores de los campos personalizados definidos en configuration.config;
    -- clave = value del campo, valor = lo capturado en el formulario.
    custom_fields jsonb not null default '{}'::jsonb
);

create table crm.contacts (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    custom_fields jsonb not null default '{}'::jsonb
);

create table crm.contact_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity (sequence name crm."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[],
    -- Tipo de actividad (nota, llamada, reunión, whatsapp, correo…); ver
    -- configuration.config.noteTypes.
    type text not null default 'note'
);

create table crm.deals (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    custom_fields jsonb not null default '{}'::jsonb,
    -- Embudo al que pertenece la oportunidad (value de un embudo definido en
    -- configuration.config.dealPipelines). El default coincide con el embudo
    -- que se sintetiza para configuraciones anteriores a los embudos múltiples.
    pipeline text not null default 'ventas',
    -- Motivo por el que se perdió (value de configuration.config.dealLossReasons).
    loss_reason text
);

create table crm.deal_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity (sequence name crm."dealNotes_id_seq") not null,
    deal_id bigint not null,
    -- Tipo de actividad (nota, llamada, reunión, whatsapp, correo…); ver
    -- configuration.config.noteTypes.
    type text not null default 'note',
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table crm.sales (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

-- La unicidad es por organización, no global: KontrolIA Auth permite que una
-- misma persona sea miembro de varias organizaciones, y en ese caso necesita
-- una ficha de comercial en cada una.
create unique index uq__sales__organization_id__user_id on crm.sales using btree (organization_id, user_id);

create table crm.automations (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    active boolean not null default true,
    -- Disparador: qué tiene que pasar (contacts|deals, created|stage_changed).
    trigger_resource text not null,
    trigger_event text not null,
    trigger_params jsonb not null default '{}'::jsonb,
    -- Acción: qué hacer entonces (create_task|assign_owner) y sus parámetros.
    action_type text not null,
    action_params jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

create index automations_organization_id_idx on crm.automations (organization_id);

create table crm.public_forms (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique default encode(extensions.gen_random_bytes(12), 'hex'),
    -- Qué crea cada envío: "lead" da de alta un contacto (y su empresa);
    -- "ticket" abre un ticket de soporte asociado al contacto que lo reporta.
    type text not null default 'lead',
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index public_forms_organization_id_idx on crm.public_forms (organization_id);

-- Un registro por envío aceptado, solo para poner un límite a cuántos puede
-- mandar un mismo formulario en poco tiempo.
create table crm.public_form_submissions (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    public_form_id bigint not null,
    created_at timestamp with time zone not null default now()
);

create index public_form_submissions_form_created_idx
    on crm.public_form_submissions (public_form_id, created_at);

create table crm.saved_views (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    -- Lista a la que pertenece la vista (contacts, companies, deals).
    resource text not null,
    name text not null,
    -- { filter, sort } tal como los maneja la lista.
    params jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create index saved_views_organization_id_idx on crm.saved_views (organization_id);

create table crm.webhooks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    url text not null,
    -- Secreto de firma (X-Vinqulia-Firma = HMAC-SHA256 hex del cuerpo).
    secret text not null default encode(extensions.gen_random_bytes(24), 'hex'),
    -- Tablas suscritas; vacío = todas las notificables.
    resources text[] not null default '{}',
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index webhooks_organization_id_idx on crm.webhooks (organization_id);

-- Claves de API: acceso de servidor a servidor para integraciones externas
-- (por ejemplo, un formulario de captación en otro sitio con sus propios
-- campos). El secreto en claro nunca se guarda, solo su hash; se genera y se
-- muestra una única vez desde /api/claves. Ver src/lib/server/apiKeys.ts.
create table crm.api_keys (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    key_prefix text not null,
    key_hash text not null unique,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    last_used_at timestamp with time zone
);

create index api_keys_organization_id_idx on crm.api_keys (organization_id);

create table crm.tags (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table crm.tasks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

-- Una fila de configuración por organización. Antes era un singleton
-- (check (id = 1)), lo que impedía que cada empresa tuviera su propia marca,
-- sus etapas de oportunidad o su moneda.
create table crm.configuration (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid primary key,
    config jsonb not null default '{}'::jsonb
);

create table crm.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

-- Ticket de soporte reportado por un cliente. Siempre va asociado a un
-- contacto y a su empresa, para que el historial de soporte quede visible
-- desde ambas fichas.
create table crm.tickets (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    subject text not null,
    description text,
    status text not null default 'open',
    contact_id bigint not null,
    company_id bigint not null,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index tickets_organization_id_idx on crm.tickets (organization_id);
create index tickets_contact_id_idx on crm.tickets (contact_id);
create index tickets_company_id_idx on crm.tickets (company_id);

create table crm.ticket_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    -- Tipo de actividad (nota, llamada, reunión, whatsapp, correo…); ver
    -- configuration.config.noteTypes.
    type text not null default 'note',
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

--
-- Foreign keys
--

alter table crm.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references crm.sales(id) on update cascade on delete cascade;

alter table crm.deals
    add constraint deals_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references crm.deals(id) on update cascade on delete cascade;

alter table crm.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references crm.sales(id);

alter table crm.public_form_submissions
    add constraint public_form_submissions_form_id_fkey foreign key (public_form_id) references crm.public_forms(id) on delete cascade;

alter table crm.saved_views
    add constraint saved_views_sales_id_fkey foreign key (sales_id) references crm.sales(id);

-- sales.user_id NO lleva clave foránea a auth.users: la identidad vive en
-- KontrolIA Auth (otro proyecto Supabase) y el auth.users local no contiene a
-- los usuarios. Es un identificador opaco que valida el servidor vía token.

alter table crm.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.ticket_notes
    add constraint ticket_notes_ticket_id_fkey foreign key (ticket_id) references crm.tickets(id) on update cascade on delete cascade;

alter table crm.ticket_notes
    add constraint ticket_notes_sales_id_fkey foreign key (sales_id) references crm.sales(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only crm.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only crm.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on crm.contact_notes using btree (contact_id);
create index contacts_company_id_idx on crm.contacts using btree (company_id);
create index deal_notes_deal_id_idx on crm.deal_notes using btree (deal_id);
create index deals_company_id_idx on crm.deals using btree (company_id);
create index ticket_notes_ticket_id_idx on crm.ticket_notes using btree (ticket_id);

-- Índices de aislamiento por organización.
-- Toda consulta del CRM lleva el filtro de RLS `organization_id = ...`, así que
-- sin estos índices cada lectura degenera en un escaneo secuencial de la tabla
-- completa en cuanto haya varias empresas dentro.
create index if not exists companies_organization_id_idx on crm.companies (organization_id);
create index if not exists contacts_organization_id_idx on crm.contacts (organization_id);
create index if not exists contact_notes_organization_id_idx on crm.contact_notes (organization_id);
create index if not exists deals_organization_id_idx on crm.deals (organization_id);
create index if not exists deal_notes_organization_id_idx on crm.deal_notes (organization_id);
create index if not exists ticket_notes_organization_id_idx on crm.ticket_notes (organization_id);
create index if not exists sales_organization_id_idx on crm.sales (organization_id);
create index if not exists tags_organization_id_idx on crm.tags (organization_id);
create index if not exists tasks_organization_id_idx on crm.tasks (organization_id);
