--
-- Tables
-- This file declares all tables in the crm schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists pg_net;

-- Esquema del CRM: todo el contenido de esta aplicacion vive aqui, separado
-- del esquema public para poder compartir el proyecto de Supabase con otras
-- aplicaciones del ecosistema KontrolIA sin colisionar nombres.
create schema if not exists crm;

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table crm.companies (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    -- Valores de los campos personalizados definidos en configuration.config;
    -- clave = value del campo, valor = lo capturado en el formulario.
    custom_fields jsonb not null default '{}'::jsonb,
    -- Módulo Afiliados: qué afiliado trajo a este cliente. Ver la clave
    -- foránea más abajo.
    referred_by_affiliate_id bigint
);

create index if not exists companies_referred_by_affiliate_id_idx
    on crm.companies (referred_by_affiliate_id);

create table crm.contacts (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    custom_fields jsonb not null default '{}'::jsonb
);

create table crm.contact_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity (sequence name crm."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[],
    -- Tipo de actividad (nota, llamada, reunión, whatsapp, correo…); ver
    -- configuration.config.noteTypes.
    type text not null default 'note'
);

create table crm.deals (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    custom_fields jsonb not null default '{}'::jsonb,
    -- Embudo al que pertenece la oportunidad (value de un embudo definido en
    -- configuration.config.dealPipelines). El default coincide con el embudo
    -- que se sintetiza para configuraciones anteriores a los embudos múltiples.
    pipeline text not null default 'ventas',
    -- Motivo por el que se perdió (value de configuration.config.dealLossReasons).
    loss_reason text
);

create table crm.deal_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity (sequence name crm."dealNotes_id_seq") not null,
    deal_id bigint not null,
    -- Tipo de actividad (nota, llamada, reunión, whatsapp, correo…); ver
    -- configuration.config.noteTypes.
    type text not null default 'note',
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table crm.sales (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

-- La unicidad es por organización, no global: KontrolIA Auth permite que una
-- misma persona sea miembro de varias organizaciones, y en ese caso necesita
-- una ficha de comercial en cada una.
create unique index uq__sales__organization_id__user_id on crm.sales using btree (organization_id, user_id);

create table crm.automations (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    active boolean not null default true,
    -- Disparador: qué tiene que pasar (contacts|deals, created|stage_changed).
    trigger_resource text not null,
    trigger_event text not null,
    trigger_params jsonb not null default '{}'::jsonb,
    -- Acción: qué hacer entonces (create_task|assign_owner) y sus parámetros.
    action_type text not null,
    action_params jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

create index automations_organization_id_idx on crm.automations (organization_id);

create table crm.public_forms (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique default encode(extensions.gen_random_bytes(12), 'hex'),
    -- Qué crea cada envío: "lead" da de alta un contacto (y su empresa);
    -- "ticket" abre un ticket de soporte asociado al contacto que lo reporta.
    type text not null default 'lead',
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index public_forms_organization_id_idx on crm.public_forms (organization_id);

-- Un registro por envío aceptado, solo para poner un límite a cuántos puede
-- mandar un mismo formulario en poco tiempo.
create table crm.public_form_submissions (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    public_form_id bigint not null,
    created_at timestamp with time zone not null default now()
);

create index public_form_submissions_form_created_idx
    on crm.public_form_submissions (public_form_id, created_at);

create table crm.saved_views (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    -- Lista a la que pertenece la vista (contacts, companies, deals).
    resource text not null,
    name text not null,
    -- { filter, sort } tal como los maneja la lista.
    params jsonb not null default '{}'::jsonb,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create index saved_views_organization_id_idx on crm.saved_views (organization_id);

create table crm.webhooks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    url text not null,
    -- Secreto de firma (X-Vinqulia-Firma = HMAC-SHA256 hex del cuerpo).
    secret text not null default encode(extensions.gen_random_bytes(24), 'hex'),
    -- Tablas suscritas; vacío = todas las notificables.
    resources text[] not null default '{}',
    -- Eventos concretos (contacts.created, deals.updated…); vacío = todos los
    -- del recurso. Es lo que permite integraciones bidireccionales sin bucle:
    -- un sistema que responde a «created» escribiendo en la ficha se suscribe
    -- solo a «created», así su propia escritura no le vuelve como «updated».
    events text[] not null default '{}',
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index webhooks_organization_id_idx on crm.webhooks (organization_id);

-- Cola de envíos. El disparador solo encola —barato y dentro de la misma
-- transacción que el cambio— y el despachador programado envía y reintenta.
-- Antes el disparador hacía el POST en el momento y se tragaba los errores:
-- un receptor caído significaba un aviso perdido para siempre.
create table crm.webhook_deliveries (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    webhook_id bigint not null,
    -- Viaja en X-Vinqulia-Evento-Id para que el receptor pueda descartar
    -- duplicados por su cuenta.
    event_id uuid not null default extensions.gen_random_uuid(),
    event text not null,
    resource text not null,
    payload jsonb not null,
    attempts integer not null default 0,
    max_attempts integer not null default 5,
    next_attempt_at timestamp with time zone not null default now(),
    delivered_at timestamp with time zone,
    -- Identificador en pg_net mientras la petición está en vuelo; se limpia
    -- al reconciliar la respuesta.
    net_request_id bigint,
    last_status_code integer,
    last_error text,
    created_at timestamp with time zone not null default now()
);

create index webhook_deliveries_pendientes_idx
    on crm.webhook_deliveries (next_attempt_at)
    where delivered_at is null;
create index webhook_deliveries_en_vuelo_idx
    on crm.webhook_deliveries (net_request_id)
    where net_request_id is not null;
create index webhook_deliveries_organization_id_idx
    on crm.webhook_deliveries (organization_id);

-- Claves de API: acceso de servidor a servidor para integraciones externas
-- (por ejemplo, un formulario de captación en otro sitio con sus propios
-- campos). El secreto en claro nunca se guarda, solo su hash; se genera y se
-- muestra una única vez desde /api/claves. Ver src/lib/server/apiKeys.ts.
create table crm.api_keys (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    key_prefix text not null,
    key_hash text not null unique,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    last_used_at timestamp with time zone
);

-- Servidor de correo saliente de la organización: por dónde salen TODOS los
-- correos que envía el CRM (envío manual desde una ficha, automatizaciones…).
--
-- Una fila por organización, de ahí la clave primaria: cada cliente envía
-- desde su propio dominio y con su propia cuenta del proveedor.
--
-- OJO con `api_key`: es un secreto reutilizable, no un hash como en
-- crm.api_keys —hay que presentarlo al proveedor en cada envío—, así que
-- esta tabla NO se expone. No tiene grants para anon/authenticated, no tiene
-- políticas RLS (nadie pasa salvo service_role), y está en la lista de
-- recursos prohibidos del puente /api/datos, que consulta con la clave de
-- servicio y sí llegaría a leerla. Se gestiona solo por /api/correos/configuracion,
-- que nunca devuelve el secreto.
-- Cola de correos que dejan encolados las automatizaciones. El disparador
-- solo encola porque armar el correo exige el diseño de plantillaBase.ts y
-- los campos de fusión de valoresDeFusion.ts, ambos en TypeScript: el
-- despachador (crm.despachar_correos) avisa a la aplicación, que es quien
-- renderiza y envía.
create table crm.email_outbox (
    organization_id uuid not null,
    id bigint generated by default as identity primary key,
    automation_id bigint,
    template_id bigint not null,
    contact_id bigint not null,
    -- La oportunidad que originó el envío, si la regla venía de un deal:
    -- es lo que permite usar {{oportunidad.*}} en la plantilla.
    deal_id bigint,
    -- El contrato que originó el envío, si la regla era de renovación:
    -- es lo que permite usar {{contrato.*}} en la plantilla.
    contract_id bigint,
    attempts integer not null default 0,
    max_attempts integer not null default 5,
    next_attempt_at timestamp with time zone not null default now(),
    sent_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone not null default now()
);

create index email_outbox_pendientes_idx
    on crm.email_outbox (next_attempt_at)
    where sent_at is null;
create index email_outbox_organization_id_idx
    on crm.email_outbox (organization_id);

-- Constancia de las automatizaciones por fecha ya disparadas: una regla no
-- actúa dos veces sobre el mismo contrato y la misma fecha de renovación
-- aunque el cron corra de más o se recupere de un día caído.
create table crm.automation_runs (
    organization_id uuid not null,
    id bigint generated by default as identity primary key,
    automation_id bigint not null,
    contract_id bigint not null,
    due_on date not null,
    created_at timestamp with time zone not null default now()
);
create unique index automation_runs_once_uk
    on crm.automation_runs (automation_id, contract_id, due_on);
create index automation_runs_organization_id_idx
    on crm.automation_runs (organization_id);

-- Ajustes de la instalación, no de una organización: el secreto con el que
-- la base autentica el despacho de correos y dónde vive la aplicación.
-- Guarda un secreto, así que va sin grants para anon/authenticated, sin
-- políticas RLS y en la lista de recursos prohibidos del puente.
create table crm.internal_settings (
    key text primary key,
    value text not null,
    updated_at timestamp with time zone not null default now()
);

-- ── Módulo Clientes ───────────────────────────────────────────────────
-- Etapa del ciclo de vida: prospecto, cliente activo, en riesgo, perdido.
-- Los valores los define cada organización en configuration.config, como el
-- resto de catálogos; aquí solo se guarda el elegido.
alter table crm.companies
    add column if not exists lifecycle_stage text;

create index if not exists companies_lifecycle_stage_idx
    on crm.companies (organization_id, lifecycle_stage);

-- Contratos y suscripciones: la relación que DURA.
--
-- Se modela con periodos y no como "una compra que se repite" porque es lo
-- que permite lo que de verdad se pregunta: qué está activo hoy, qué vence el
-- mes que viene, qué se pausó y qué cambió de importe por el camino.
create table crm.contracts (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    name text not null,
    -- active | paused | cancelled | expired
    status text not null default 'active',
    -- monthly | quarterly | yearly | one_time
    billing_period text,
    amount numeric,
    currency text not null default 'MXN',
    started_on date,
    -- Próxima renovación o vencimiento: es la fecha sobre la que se avisa.
    renews_on date,
    ended_on date,
    auto_renew boolean not null default true,
    -- De dónde salió: manual, faqturia, el ERP del cliente, una tienda…
    source text not null default 'manual',
    external_id text,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Compras: los HECHOS puntuales (una factura, un pedido, un cobro).
create table crm.purchases (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    -- Si la compra corresponde a un contrato (una mensualidad, por ejemplo).
    contract_id bigint,
    -- Número visible en el sistema de origen (folio de factura, nº de pedido).
    reference text,
    purchased_on date not null default current_date,
    amount numeric not null default 0,
    currency text not null default 'MXN',
    -- paid | pending | cancelled | refunded
    status text not null default 'paid',
    source text not null default 'manual',
    external_id text,
    created_at timestamp with time zone not null default now()
);

-- Líneas de la compra: el QUÉ. `description` y `unit_price` son la foto del
-- momento; `product_ref` es el identificador del producto en el sistema de
-- origen, que es lo que permite preguntar «quién tiene X y no Y».
create table crm.purchase_items (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    purchase_id bigint not null,
    description text not null,
    product_ref text,
    quantity numeric not null default 1,
    unit_price numeric,
    amount numeric
);

create index contracts_company_id_idx on crm.contracts (company_id);
create index contracts_renews_on_idx on crm.contracts (organization_id, renews_on)
    where status = 'active';
create index purchases_company_id_idx on crm.purchases (company_id);
create index purchases_purchased_on_idx on crm.purchases (organization_id, purchased_on);
create index purchase_items_purchase_id_idx on crm.purchase_items (purchase_id);
create index purchase_items_product_ref_idx on crm.purchase_items (organization_id, product_ref);

-- Idempotencia de la integración: si el sistema de origen reenvía la misma
-- factura —y lo hará, por un reintento o una resincronización— no debe
-- duplicarse. Es la diferencia entre una integración que sirve y una que
-- ensucia la base.
create unique index contracts_source_external_uk
    on crm.contracts (organization_id, source, external_id)
    where external_id is not null;
create unique index purchases_source_external_uk
    on crm.purchases (organization_id, source, external_id)
    where external_id is not null;


create table crm.email_settings (
    organization_id uuid not null primary key default (auth.jwt() ->> 'organization_id')::uuid,
    provider text not null check (provider in ('resend', 'postmark', 'sendgrid')),
    api_key text not null,
    from_email text not null,
    from_name text,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index api_keys_organization_id_idx on crm.api_keys (organization_id);

create table crm.tags (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table crm.tasks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

-- Una fila de configuración por organización. Antes era un singleton
-- (check (id = 1)), lo que impedía que cada empresa tuviera su propia marca,
-- sus etapas de oportunidad o su moneda.
create table crm.configuration (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid primary key,
    config jsonb not null default '{}'::jsonb
);

create table crm.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

-- Ticket de soporte reportado por un cliente. Siempre va asociado a un
-- contacto y a su empresa, para que el historial de soporte quede visible
-- desde ambas fichas.
create table crm.tickets (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    subject text not null,
    description text,
    status text not null default 'open',
    contact_id bigint not null,
    company_id bigint not null,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index tickets_organization_id_idx on crm.tickets (organization_id);
create index tickets_contact_id_idx on crm.tickets (contact_id);
create index tickets_company_id_idx on crm.tickets (company_id);

create table crm.ticket_notes (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    -- Tipo de actividad (nota, llamada, reunión, whatsapp, correo…); ver
    -- configuration.config.noteTypes.
    type text not null default 'note',
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

-- Afiliado: un contacto que llegó a la etapa de "afiliación completa" del
-- embudo configurado en el módulo Afiliados (ver crm.gestionar_modulo_afiliados
-- en 02_functions.sql). El módulo entero puede estar apagado por organización
-- sin que esta tabla deje de existir — solo deja de recibir filas nuevas.
create table crm.affiliates (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    company_id bigint not null,
    -- Oportunidad ganada que originó la afiliación. Puede quedar sin dueño si
    -- el deal se borra; el afiliado en sí no depende de que siga existiendo.
    deal_id bigint,
    -- El {id} de la URL de referidos (config.modules.affiliates.urlTemplate).
    -- Formato de slug: minúsculas, dígitos y guiones, sin empezar ni terminar
    -- en guión, para que sea válido en una URL sin escaparlo.
    referral_code text not null
        check (referral_code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    commission_percentage numeric,
    active boolean not null default true,
    -- Vínculo manual: el administrador lo rellena después de crear la cuenta
    -- en KontrolIA Auth. Mientras esté vacío, este contacto es afiliado pero
    -- nadie puede iniciar sesión "como" él.
    kontrolia_auth_user_id uuid,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create unique index affiliates_organization_contact_uk
    on crm.affiliates (organization_id, contact_id);
create unique index affiliates_organization_referral_code_uk
    on crm.affiliates (organization_id, referral_code);
create index affiliates_organization_id_idx on crm.affiliates (organization_id);
create index affiliates_kontrolia_auth_user_id_idx
    on crm.affiliates (kontrolia_auth_user_id);

--
-- Foreign keys
--

alter table crm.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references crm.sales(id) on update cascade on delete cascade;

alter table crm.deals
    add constraint deals_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references crm.deals(id) on update cascade on delete cascade;

alter table crm.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references crm.sales(id);

alter table crm.public_form_submissions
    add constraint public_form_submissions_form_id_fkey foreign key (public_form_id) references crm.public_forms(id) on delete cascade;

alter table crm.saved_views
    add constraint saved_views_sales_id_fkey foreign key (sales_id) references crm.sales(id);

-- sales.user_id NO lleva clave foránea a auth.users: la identidad vive en
-- KontrolIA Auth (otro proyecto Supabase) y el auth.users local no contiene a
-- los usuarios. Es un identificador opaco que valida el servidor vía token.

alter table crm.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.tickets
    add constraint tickets_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.ticket_notes
    add constraint ticket_notes_ticket_id_fkey foreign key (ticket_id) references crm.tickets(id) on update cascade on delete cascade;

alter table crm.ticket_notes
    add constraint ticket_notes_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.affiliates
    add constraint affiliates_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on update cascade on delete cascade;

alter table crm.affiliates
    add constraint affiliates_company_id_fkey foreign key (company_id) references crm.companies(id) on update cascade on delete cascade;

alter table crm.affiliates
    add constraint affiliates_deal_id_fkey foreign key (deal_id) references crm.deals(id) on update cascade on delete set null;

alter table crm.affiliates
    add constraint affiliates_sales_id_fkey foreign key (sales_id) references crm.sales(id);

alter table crm.webhook_deliveries
    add constraint webhook_deliveries_webhook_id_fkey foreign key (webhook_id) references crm.webhooks(id) on delete cascade;

alter table crm.email_outbox
    add constraint email_outbox_template_id_fkey foreign key (template_id) references crm.email_templates(id) on delete cascade;
alter table crm.email_outbox
    add constraint email_outbox_contact_id_fkey foreign key (contact_id) references crm.contacts(id) on delete cascade;
alter table crm.email_outbox
    add constraint email_outbox_deal_id_fkey foreign key (deal_id) references crm.deals(id) on delete set null;
alter table crm.email_outbox
    add constraint email_outbox_contract_id_fkey foreign key (contract_id) references crm.contracts(id) on delete cascade;

alter table crm.automation_runs
    add constraint automation_runs_automation_id_fkey foreign key (automation_id) references crm.automations(id) on delete cascade,
    add constraint automation_runs_contract_id_fkey foreign key (contract_id) references crm.contracts(id) on delete cascade;

alter table crm.contracts
    add constraint contracts_company_id_fkey
    foreign key (company_id) references crm.companies(id) on delete cascade;
alter table crm.contracts
    add constraint contracts_sales_id_fkey
    foreign key (sales_id) references crm.sales(id);

alter table crm.purchases
    add constraint purchases_company_id_fkey
    foreign key (company_id) references crm.companies(id) on delete cascade;
alter table crm.purchases
    add constraint purchases_contract_id_fkey
    foreign key (contract_id) references crm.contracts(id) on delete set null;

alter table crm.purchase_items
    add constraint purchase_items_purchase_id_fkey
    foreign key (purchase_id) references crm.purchases(id) on delete cascade;

-- Atribución: qué afiliado trajo a este cliente. Se marca en la EMPRESA, no
-- en cada oportunidad, porque la comisión es sobre "los pagos de los clientes
-- referenciados" — todo lo que ese cliente compre después cuenta, sin que
-- quien capta el lead tenga que repetir el código de referido cada vez.
--
-- Es de primer toque: una vez asignado no se reasigna (ver
-- crm.conservar_afiliado_de_referencia en 02_functions.sql).
alter table crm.companies
    add constraint companies_referred_by_affiliate_id_fkey
    foreign key (referred_by_affiliate_id) references crm.affiliates(id) on delete set null;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only crm.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only crm.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on crm.contact_notes using btree (contact_id);
create index contacts_company_id_idx on crm.contacts using btree (company_id);
create index deal_notes_deal_id_idx on crm.deal_notes using btree (deal_id);
create index deals_company_id_idx on crm.deals using btree (company_id);
create index ticket_notes_ticket_id_idx on crm.ticket_notes using btree (ticket_id);

-- Índices de aislamiento por organización.
-- Toda consulta del CRM lleva el filtro de RLS `organization_id = ...`, así que
-- sin estos índices cada lectura degenera en un escaneo secuencial de la tabla
-- completa en cuanto haya varias empresas dentro.
create index if not exists companies_organization_id_idx on crm.companies (organization_id);
create index if not exists contacts_organization_id_idx on crm.contacts (organization_id);
create index if not exists contact_notes_organization_id_idx on crm.contact_notes (organization_id);
create index if not exists deals_organization_id_idx on crm.deals (organization_id);
create index if not exists deal_notes_organization_id_idx on crm.deal_notes (organization_id);
create index if not exists ticket_notes_organization_id_idx on crm.ticket_notes (organization_id);
create index if not exists sales_organization_id_idx on crm.sales (organization_id);
create index if not exists tags_organization_id_idx on crm.tags (organization_id);
create index if not exists tasks_organization_id_idx on crm.tasks (organization_id);
