-- Automatizaciones: «cuando pase X, haz Y».
--
-- «Cuando una oportunidad llegue a Propuesta, créame una tarea de seguimiento
-- a 3 días.» «Cuando entre un contacto nuevo, asígnalo a Raúl.» Reglas en
-- lenguaje llano, sin diagramas de flujo.
--
-- Viven en la base y no en la aplicación por la misma razón que los webhooks:
-- así se aplican venga la escritura de donde venga (aplicación, API o
-- importación). Como las acciones son escrituras en la propia base, no hace
-- falta salir a la red.

create table public.automations (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    active boolean not null default true,
    -- Disparador: qué tiene que pasar.
    trigger_resource text not null,          -- contacts | deals
    trigger_event text not null,             -- created | stage_changed
    trigger_params jsonb not null default '{}'::jsonb,  -- { stage }
    -- Acción: qué hacer entonces.
    action_type text not null,               -- create_task | assign_owner
    action_params jsonb not null default '{}'::jsonb,   -- { text, taskType, dueInDays } | { salesId }
    created_at timestamp with time zone not null default now()
);

create index automations_organization_id_idx on public.automations (organization_id);

alter table public.automations enable row level security;

create policy "Automations are scoped to the organization" on public.automations
    for select to authenticated
    using (organization_id = public.current_organization_id());
create policy "Automations are created in the organization" on public.automations
    for insert to authenticated
    with check (organization_id = public.current_organization_id());
create policy "Automations are updated within the organization" on public.automations
    for update to authenticated
    using (organization_id = public.current_organization_id())
    with check (organization_id = public.current_organization_id());
create policy "Automations are deleted within the organization" on public.automations
    for delete to authenticated
    using (organization_id = public.current_organization_id());

grant select, insert, update, delete on table public.automations to anon, authenticated, service_role;
grant usage, select on sequence public.automations_id_seq to anon, authenticated, service_role;

-- El motor. Se ejecuta después de cada alta (y de cada cambio de etapa en
-- oportunidades) y aplica las reglas activas de esa organización.
create or replace function public.run_automations() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  org uuid;
  evento text;
  etapa text;
  regla record;
  contacto bigint;
  responsable bigint;
begin
  -- Guarda contra cascadas: una acción que escribe (asignar responsable)
  -- volvería a disparar el motor y podría no terminar nunca.
  if pg_trigger_depth() > 1 then
    return null;
  end if;

  org := new.organization_id;
  if org is null then
    return null;
  end if;

  if tg_op = 'INSERT' then
    evento := 'created';
  elsif tg_table_name = 'deals' and new.stage is distinct from old.stage then
    -- Solo el cambio de etapa cuenta: al crear ya se notificó como 'created'.
    evento := 'stage_changed';
  else
    return null;
  end if;

  -- La etapa se lee ANTES de la consulta y solo donde existe la columna:
  -- PL/pgSQL prepara la consulta entera, así que una referencia a new.stage
  -- dentro de ella fallaría en contacts aunque la condición nunca se cumpla.
  if tg_table_name = 'deals' then
    etapa := new.stage;
  end if;

  -- Todo el motor va protegido: ni una regla mal configurada ni un fallo
  -- interno pueden tumbar la escritura que lo disparó.
  begin
    for regla in
      select * from public.automations
      where organization_id = org
        and active
        and trigger_resource = tg_table_name
        and trigger_event = evento
        and (
          evento <> 'stage_changed'
          or trigger_params ->> 'stage' is null
          or trigger_params ->> 'stage' = etapa
        )
    loop
      begin
        if regla.action_type = 'create_task' then
          -- Las tareas cuelgan siempre de un contacto. En una oportunidad se
          -- usa su primer contacto; si no tiene ninguno, la regla se salta.
          if tg_table_name = 'contacts' then
            contacto := new.id;
          else
            contacto := new.contact_ids[1];
          end if;

          if contacto is not null then
            insert into public.tasks
              (organization_id, contact_id, text, type, due_date, sales_id)
            values (
              org,
              contacto,
              coalesce(nullif(regla.action_params ->> 'text', ''), regla.name),
              nullif(regla.action_params ->> 'taskType', ''),
              now() + (
                coalesce((regla.action_params ->> 'dueInDays')::int, 3) || ' days'
              )::interval,
              new.sales_id
            );
          end if;

        elsif regla.action_type = 'assign_owner' then
          responsable := nullif(regla.action_params ->> 'salesId', '')::bigint;
          if responsable is not null then
            if tg_table_name = 'contacts' then
              update public.contacts set sales_id = responsable where id = new.id;
            else
              update public.deals set sales_id = responsable where id = new.id;
            end if;
          end if;
        end if;
      exception when others then
        null; -- una regla concreta falla, las demás siguen
      end;
    end loop;
  exception when others then
    null; -- el motor nunca bloquea la escritura original
  end;

  return null;
end;
$$;

grant all on function public.run_automations() to authenticated;
grant all on function public.run_automations() to service_role;

create trigger run_automations_contacts
    after insert on public.contacts
    for each row execute function public.run_automations();

create trigger run_automations_deals
    after insert or update on public.deals
    for each row execute function public.run_automations();
