-- Formularios públicos de captación: un enlace o iframe que el cliente pega
-- en su propia página web y que crea contactos solo, sin que nadie del
-- equipo los capture a mano.
--
-- `slug` es la clave pública: identifica a qué organización pertenece un
-- envío SIN sesión de por medio (quien rellena el formulario nunca ha
-- iniciado sesión). Por eso es impredecible (bytes aleatorios, no un
-- correlativo) — adivinarlo no debe ser más fácil que adivinar cualquier
-- otro identificador opaco del sistema.
create table public.public_forms (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique default encode(extensions.gen_random_bytes(12), 'hex'),
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index public_forms_organization_id_idx on public.public_forms (organization_id);

alter table public.public_forms enable row level security;

-- Estas políticas protegen únicamente la administración (quién puede ver o
-- editar la lista de formularios de su organización). El envío público en sí
-- nunca pasa por aquí: lo atiende una ruta de servidor con la clave de
-- servicio, que resuelve la organización a partir del slug sin sesión.
create policy "Public forms are scoped to the organization" on public.public_forms
    for select to authenticated
    using (organization_id = public.current_organization_id());
create policy "Public forms are created in the organization" on public.public_forms
    for insert to authenticated
    with check (organization_id = public.current_organization_id());
create policy "Public forms are updated within the organization" on public.public_forms
    for update to authenticated
    using (organization_id = public.current_organization_id())
    with check (organization_id = public.current_organization_id());
create policy "Public forms are deleted within the organization" on public.public_forms
    for delete to authenticated
    using (organization_id = public.current_organization_id());

grant select, insert, update, delete on table public.public_forms to anon, authenticated, service_role;
grant usage, select on sequence public.public_forms_id_seq to anon, authenticated, service_role;

-- Un registro por envío aceptado, solo para poner un límite a cuántos puede
-- mandar un mismo formulario en poco tiempo. Vive en la base y no en memoria
-- del proceso: cada invocación de la ruta pública puede correr en una
-- instancia de servidor distinta, así que un contador en memoria no
-- protegería nada.
create table public.public_form_submissions (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    public_form_id bigint not null references public.public_forms(id) on delete cascade,
    created_at timestamp with time zone not null default now()
);

create index public_form_submissions_form_created_idx
    on public.public_form_submissions (public_form_id, created_at);

alter table public.public_form_submissions enable row level security;

create policy "Public form submissions are scoped to the organization" on public.public_form_submissions
    for select to authenticated
    using (organization_id = public.current_organization_id());

grant select, insert on table public.public_form_submissions to anon, authenticated, service_role;
grant usage, select on sequence public.public_form_submissions_id_seq to anon, authenticated, service_role;

-- «Formulario web» como sexto tipo de actividad de fábrica: la nota que deja
-- un envío público queda tipificada igual que una llamada o una reunión.
update public.configuration
set config = jsonb_set(
    config,
    '{noteTypes}',
    (config -> 'noteTypes') || '[{"value":"web","label":"Formulario web"}]'::jsonb
)
where config ? 'noteTypes'
  and not exists (
    select 1 from jsonb_array_elements(config -> 'noteTypes') as tipo
    where tipo ->> 'value' = 'web'
  );
