-- Webhooks salientes: «avísale a mi sistema cuando algo cambie».
--
-- Cada organización da de alta URLs suscritas; un disparador a nivel de base
-- notifica cada alta, cambio o baja en las tablas principales, sin importar
-- por dónde entró la escritura (aplicación, API o importación). Con esto
-- cualquier cliente conecta n8n, Zapier o Make sin que Vinqulia construya
-- cada integración.
--
-- La entrega usa pg_net (asíncrona, no bloquea la escritura) y va firmada:
-- X-Vinqulia-Firma = HMAC-SHA256 hex del cuerpo con el secreto del webhook,
-- para que el receptor verifique que el aviso es legítimo. v1 sin reintentos.

create extension if not exists pg_net;

create table public.webhooks (
    organization_id uuid not null default (auth.jwt() ->> 'organization_id')::uuid,
    id bigint generated by default as identity primary key,
    url text not null,
    -- Secreto de firma, generado por la base: nunca viaja en claro fuera de
    -- la organización.
    secret text not null default encode(extensions.gen_random_bytes(24), 'hex'),
    -- Tablas suscritas; vacío = todas las notificables.
    resources text[] not null default '{}',
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create index webhooks_organization_id_idx on public.webhooks (organization_id);

alter table public.webhooks enable row level security;

create policy "Webhooks are scoped to the organization" on public.webhooks
    for select to authenticated
    using (organization_id = public.current_organization_id());
create policy "Webhooks are created in the organization" on public.webhooks
    for insert to authenticated
    with check (organization_id = public.current_organization_id());
create policy "Webhooks are updated within the organization" on public.webhooks
    for update to authenticated
    using (organization_id = public.current_organization_id())
    with check (organization_id = public.current_organization_id());
create policy "Webhooks are deleted within the organization" on public.webhooks
    for delete to authenticated
    using (organization_id = public.current_organization_id());

-- El disparador: arma el evento (recurso.created/updated/deleted), firma el
-- cuerpo y lo envía a cada webhook activo de la organización de la fila.
-- Cada entrega va protegida: un webhook caído JAMÁS debe romper la escritura
-- que lo originó.
create or replace function public.notify_webhooks() returns trigger
    language plpgsql security definer
    set search_path = ''
    as $$
declare
  registro jsonb;
  org uuid;
  evento text;
  suscripcion record;
  cuerpo jsonb;
  firma text;
begin
  if tg_op = 'DELETE' then
    registro := to_jsonb(old);
  else
    registro := to_jsonb(new);
  end if;

  org := (registro ->> 'organization_id')::uuid;
  if org is null then
    return null;
  end if;

  evento := tg_table_name || '.' || case tg_op
    when 'INSERT' then 'created'
    when 'UPDATE' then 'updated'
    else 'deleted'
  end;

  for suscripcion in
    select id, url, secret from public.webhooks
    where organization_id = org
      and active
      and (resources = '{}' or tg_table_name = any(resources))
  loop
    begin
      cuerpo := jsonb_build_object(
        'evento', evento,
        'recurso', tg_table_name,
        'fecha', now(),
        'datos', registro
      );
      firma := encode(
        extensions.hmac(cuerpo::text, suscripcion.secret, 'sha256'),
        'hex'
      );
      perform net.http_post(
        url := suscripcion.url,
        body := cuerpo,
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'X-Vinqulia-Evento', evento,
          'X-Vinqulia-Firma', firma
        )
      );
    exception when others then
      null; -- la escritura original nunca se sacrifica por un aviso
    end;
  end loop;

  return null;
end;
$$;

grant all on function public.notify_webhooks() to authenticated;
grant all on function public.notify_webhooks() to service_role;

create trigger notify_webhooks_contacts
    after insert or update or delete on public.contacts
    for each row execute function public.notify_webhooks();
create trigger notify_webhooks_companies
    after insert or update or delete on public.companies
    for each row execute function public.notify_webhooks();
create trigger notify_webhooks_deals
    after insert or update or delete on public.deals
    for each row execute function public.notify_webhooks();
create trigger notify_webhooks_tasks
    after insert or update or delete on public.tasks
    for each row execute function public.notify_webhooks();
create trigger notify_webhooks_contact_notes
    after insert or update or delete on public.contact_notes
    for each row execute function public.notify_webhooks();
create trigger notify_webhooks_deal_notes
    after insert or update or delete on public.deal_notes
    for each row execute function public.notify_webhooks();

-- Grants explícitos: los default privileges de la instalación pueden estar
-- definidos por otro rol y no cubrir tablas creadas después.
grant select, insert, update, delete on table public.webhooks to anon, authenticated, service_role;
grant usage, select on sequence public.webhooks_id_seq to anon, authenticated, service_role;
